---
name: build
on:
  pull_request:
  push:
  schedule:
    - cron: "0 6 * * SUN"
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        config:
          - config/ping-esp32.yaml
          - config/ping.yaml
          - config/influxdb.yaml
          - config/ping-esp32c3.yaml
        esphome_version:
          - default
          - latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install python
        uses: actions/setup-python@v2
        with:
          python-version: '3.8'

      - name: Install pipenv
        run: |
          pip install --user pipenv

      - name: Run pipenv
        run: |
          pipenv install

      - name: Upgrade esphome to the latest if esphome_version is latest
        if: matrix.esphome_version == 'latest'
        run: |
          pipenv update "esphome"

      - name: Compile ping.yaml
        run: |
          cp config/secrets.yaml.dist config/secrets.yaml
          pipenv run esphome version
          pipenv run esphome compile ${{ matrix.config }}
