#########################################################
#                                                                                                               
#             Main Configuration Settings...                                                
#                                                                                                               
#########################################################

default_config:
python_script:
momentary:
wake_on_lan:

google:
  client_id: !secret google_calendarE_id
  client_secret: !secret google_calendarE_secret

tts:
  - platform: google_translate
    service_name: google_say
    time_memory: 300

notify_events:
  token: !secret notify_token

zone: !include zones.yaml
group: !include groups.yaml
scene: !include scenes.yaml
timer: !include timers.yaml
light: !include lights.yaml
cover: !include cover.yaml
pyscript: !include pyscript.yaml
alert: !include alerts.yaml
frontend: !include frontend.yaml
lovelace: !include lovelace.yaml
input_number: !include input_number.yaml
input_datetime: !include input_datetime.yaml
input_select: !include input_select.yaml
input_boolean: !include input_boolean.yaml
emulated_hue: !include emulated_hue.yaml
shell_command: !include shell_commands.yaml
utility_meter: !include utility_meter.yaml

binary_sensor: !include_dir_merge_list binary_sensors/
automation: !include_dir_merge_list automation/
sensor: !include_dir_merge_list sensors/
switch: !include_dir_merge_list switches/
notify: !include_dir_merge_list notify/
script: !include_dir_merge_named scripts/

homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: 20
  unit_system: metric
  time_zone: Asia/Tokyo
  internal_url: !secret internal_url
  customize: !include customize.yaml
  packages: !include_dir_named packages
  allowlist_external_dirs:
    - '/config'

# https://community.home-assistant.io/t/reverse-proxy-error/312936
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.15  #Ngnix

recorder:
  db_url: !secret MySQL_login
  purge_keep_days: 29
  commit_interval: 10
  exclude:
    domains:
     - group
     - automation
     - camera
     - media_player
     - scene
     - script
    entities:
     - sun.sun
     - sensor.date_time


#########################################################
#                                                                                                              
#             Device Tracker                                                                             
#                                                                                                              
#########################################################

person:
  - name: Shion
    id: shion0614
    device_trackers:
     - device_tracker.shion
  - name: Eri
    id: eri1118
    device_trackers:
     - device_tracker.ie


#########################################################
#                                                                                                              
#             Sensor Integrations                                                                       
#                                                                                                              
#########################################################

rest:
  - resource: !secret switchbot_wohumi_url
    scan_interval: 900
    method: GET    
    headers:
      Authorization: !secret switchbot_api
      Content-Type: 'application/json'
    sensor:
      - name: SB Humidifier Power
        value_template: "{{ value_json.body.power }}"
        device_class: power
    
      - name: SB Humidifier Lack Water
        value_template: "{{ value_json.body.lackWater }}"
        device_class: carbon_dioxide
      - name: SB Humidifier Nebulization Efficiency
        value_template: "{{ value_json.body.nebulizationEfficiency }}"
        unit_of_measurement: '%'        
        device_class: ozone 
      - name: SB Humidifier Temperature
        value_template: "{{ value_json.body.temperature }}"
        unit_of_measurement: '°C'
        device_class: temperature 
      - name: SB Humidifier Humidity
        value_template: "{{ value_json.body.humidity }}"
        unit_of_measurement: '%'
        device_class: humidity

# Tomorrowio Pollen Count
  - resource: !secret tomorrowio_pollen_api
    scan_interval: 600
    sensor:
    ### Pollen - Tree Index
      - name: "Pollen - Tree Index - Day 0"
        value_template: "{{ value_json.data.timelines[0].intervals[0]['values']['treeIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[0].values"
        json_attributes:
        - grassIndex
        - weedIndex
        - temperature
      - name: "Pollen - Tree Index - Day 1"
        value_template: "{{ value_json.data.timelines[0].intervals[1]['values']['treeIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[1].values"
        json_attributes:
        - grassIndex
        - weedIndex
        - temperature     
      - name: "Pollen - Tree Index - Day 2"
        value_template: "{{ value_json.data.timelines[0].intervals[2]['values']['treeIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[2].values"
        json_attributes:
        - grassIndex
        - weedIndex
        - temperature
      - name: "Pollen - Tree Index - Day 3"
        value_template: "{{ value_json.data.timelines[0].intervals[3]['values']['treeIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[3].values"
        json_attributes:
        - grassIndex
        - weedIndex
        - temperature
      - name: "Pollen - Tree Index - Day 4"
        value_template: "{{ value_json.data.timelines[0].intervals[4]['values']['treeIndex'] }}"
        json_attributes_path: "$.data.timelines[0].intervals[4].values"
        json_attributes:
        - grassIndex
        - weedIndex
        - temperature

#########################################################
#                                                                                                              
#             Integration                                                                                  
#                                                                                                              
#########################################################

#alarm_control_panel:
#  - platform: manual
#    name: Home Alarm
#    code: !secret alarm_code
#    arming_time: 30
#    delay_time: 30
#    trigger_time: 1

alexa_media:
  accounts:
    - email: !secret amazon_user
      password: !secret amazon_password
      url: amazon.com
      include_devices:
       - Ai.1
       - Ai.2
       - Ai.3
       - Ai.4
# Find Amazon dot name
# https://alexa.amazon.com/api/devices-v2/device
# reaunthenicate issue - enter random string and hit submit to refresh visable captacha.

telegram_bot:
  - platform: polling
    api_key: !secret telegram_apikey
    allowed_chat_ids:
     - !secret telegram_chatid
     - !secret telegram_userid

counter:
  dining_lights_toggle:
    initial: 1
    step: 1
#Glade
  toilet_airfreshener:
    initial: 1
    step: 1
    restore: true
    icon: mdi:spray
# humidifier
#  humidifier_toggle:
#    initial: 0
#    step: 1

input_text:
  slack_app_verification_token:
    initial: !secret slack_app_verification_token
    mode: password

  room_presence:
    name: Room Presence
  


  alexa_actionable_notification:
    name: Alexa Actionable Notification Holder
    max: 255
    initial: '{"text": "This is a test of the alexa actions custom skill. Did it work?", "event": "actionable.skill.test"}'


#################
  status_fan_speed:
    name: Status Fan Speed


fan:
  - platform: template
    fans:
      yuasa_fan:
        speed_count: 3
        value_template: "{{ states('input_boolean.status_fan_power') }}"
        percentage_template: "{{ states('input_text.status_fan_speed') | int }}"
        turn_on:
          - condition: state
            entity_id: input_boolean.status_fan_power
            state: 'off'
          - service: remote.send_command
            data:
              entity_id: remote.rm4_remote
              device: Yuasa Fan
              command: power
          - service: input_boolean.turn_on
            entity_id: input_boolean.status_fan_power
        turn_off:
          - service: remote.send_command
            data:
              entity_id: remote.rm4_remote
              device: Yuasa Fan
              command: power
          - service: input_boolean.turn_off
            entity_id: input_boolean.status_fan_power

        set_percentage:
          - service: python_script.fan_speed_control
            data_template:
              fan_speed: "{{ percentage }}"
              fan_speed_entity_id: 'input_text.status_fan_speed'
              fan_entity_id: 'fan.yuasa_fan'
              fan_speed_count: 3
              service_domain: 'remote'
              service: 'send_command'
              service_data_increase:
                entity_id: remote.rm4_remote
                device: Yuasa Fan
                command: speed
              service_data_decrease:
                entity_id: remote.rm4_remote
                device: Yuasa Fan
                command: speed


#################


rest_command:
  slack_api:
    url: https://slack.com/api/{{ api }}
    content_type: 'application/json; charset=utf-8'
    verify_ssl: true
    method: 'post'
    timeout: 20
    headers:
      Authorization: !secret slackbot_token
    payload: '{{ payload }}'

# Slack URL '***-ga64322.slack.com'
  slack_response:
    url: '{{ response_url }}'
    content_type: 'application/json; charset-utf-8'
    verify_ssl: true
    method: 'post'
    timeout: 20
    payload: >
      {
         "replace_original": '{{ replace_original if (replace_original is defined) else 'true' }}',
        "text": "{{ message | default('') }}",
        "attachments": {{ attachments if (attachments is defined) else '[]' }}
      }

### Switchbot API Command
#  switchbot_device_command:
#    url: "https://api.switch-bot.com/v1.0/devices/{{ deviceId }}/commands"
#    method: post
#    content_type: "application/json"
#    headers:
#      Authorization: !secret switchbot_api
#    payload: '{ "command": "{{ command }}", "parameter": "{{ parameter }}" }' 



#########################################################
#                                                                                                              #
#             Panel Redirect                                                                              #
#                                                                                                              #
#########################################################

panel_custom:
  - name: panel-redirect
    url_path: redirect-Zigbee2mqtt-controls
    sidebar_title: Z2M Controls
    sidebar_icon: mdi:graphql
    module_url: /local/custom_ui/panel-redirect.js
    config:
      target: /hassio/ingress/45df7312_zigbee2mqtt

  - name: panel-redirect
    url_path: redirect-server-controls
    sidebar_title: Server Controls
    sidebar_icon: mdi:server
    module_url: /local/custom_ui/panel-redirect.js
    config:
      target: /developer-tools/yaml

  - name: panel-redirect
    url_path: redirect-system
    sidebar_title: System
    sidebar_icon: mdi:home-assistant
    module_url: /local/custom_ui/panel-redirect.js
    config:
      target: /config/system


#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################