####################################################
#                                                                                                    
#            MQTT Motion Sensors                                                                                
#                                                                                                    
####################################################

  - name: "motion kitchen occupancy"
    state_topic: "switchbotmqtt/esp32/motion/motion_kitchen_occupancy"
    value_template: '{{ value }}'
    payload_on: "ON"
    qos: 0
    device_class: motion

# TESTING 
#  - name: "motion k1 occupancy"
#    state_topic: "esphome/kitchen-sensor/binary_sensor/motion_k1_occupancy/state"
#    value_template: '{{ value }}'
#    payload_on: "ON"
#    qos: 0
#    device_class: motion

#  - name: "motion hallway occupancy"
#    state_topic: "esphome/hallway-sensor/binary_sensor/motion_hallway_occupancy/state"
#    value_template: '{{ value }}'
#    payload_on: "ON"
#    qos: 0
#    device_class: motion


####################################################
#                                                                                                    
#            MQTT ESP Device Connectivities                                                                            
#                                                                                                    
####################################################

#  - name: "hallway sensor status"
#    state_topic: "esphome/hallway-sensor/status"
#    value_template: '{{ value }}'
#    payload_on: "online"
#    qos: 0
#    device_class: connectivity


#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                      
#                                                                                                              
#########################################################