sensor:
  - platform: bme680
    address: 0x77
    update_interval: 15s
    temperature:
      id: temp
      name: Temperature
      oversampling: 16x
    pressure:
      id: pressure
      name: Pressure
    humidity:
      id: humidity
      name: Humidity
    gas_resistance:
      id: gas_resistance
      name: Gas Resistance
      filters:
      # Filter out sporadic power-up mega ohm values
      - lambda: if (x > 1000000) { return {}; } return x;
