
uart:
  - id: uart_0
    tx_pin: GPIO18
    rx_pin: GPIO33
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  - id: ld2410_0
    timeout: 150s
    uart_id: uart_0

light:
  - platform: status_led
    name: sys_status
    pin: GPIO15
    internal: True
    restore_mode: ALWAYS_OFF

time:
  - platform: sntp
    id: time_sntp

sensor:
  - platform: internal_temperature
    id: sys_esp_temperature
    name: ESP Temperature
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 45s
    entity_category: "diagnostic"

  - platform: uptime
    name: Uptime
    id: sys_uptime
    update_interval: 10s

  - platform: wifi_signal # consolidate
    name: RSSI
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

  - platform: ld2410
    ld2410_id: ld2410_0
    moving_distance:
      name: Moving Distance
      id: moving_distance
      disabled_by_default: true
    still_distance:
      name: Still Distance
      id: still_distance
      disabled_by_default: true
    moving_energy:
      name: Move Energy
      disabled_by_default: true
    still_energy:
      name: Still Energy
      disabled_by_default: true
    detection_distance:
      name: Detection Distance
      disabled_by_default: true
    light:
      name: Sun Light

binary_sensor:
  - platform: status # consolidate
    name: Online
    id: ink_ha_connected

  - platform: ld2410
    ld2410_id: ld2410_0
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target

button:
  - platform: template
    name: Enable LD2410 BLE
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth
    on_press:
      lambda: |-
        id(ld2410_0) -> ble_control(true);

  - platform: template
    name: Disable LD2410 BLE
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth-off
    on_press:
      lambda: |-
        id(ld2410_0) -> ble_control(false);

  - platform: template
    name: LD2410 Reboot
    icon: mdi:radar
    entity_category: "config"
    on_press:
      lambda: |-
        // auto* radar = LD2410Component::get(ld2410);
        // radar -> roboot();
        id(ld2410_0) -> reboot();

  - platform: restart
    icon: mdi:power-cycle
    name: ESP Reboot

  - platform: factory_reset
    disabled_by_default: True
    name: Factory Reset
    id: factory_reset_all
