
uart:
  id: uart_1
  tx_pin: TX
  rx_pin: RX
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

ld2410:
  id: ld2410_radar

sensor:
  - platform: ld2410
    moving_distance:
      name: Moving Distance
      disabled_by_default: true
    still_distance:
      name: Still Distance
      disabled_by_default: true
    moving_energy:
      name: Move Energy
      disabled_by_default: true
    still_energy:
      name: Still Energy
      disabled_by_default: true
    detection_distance:
      name: Detection Distance
      disabled_by_default: true

binary_sensor:
  - platform: ld2410
    has_target:
      name: Presence
    has_moving_target:
      name: Moving Target
    has_still_target:
      name: Still Target