
uart:
  - id: uart_1
    rx_pin: D2
    baud_rate: 9600
  - id: uart_2
    rx_pin: D3
    tx_pin: D4
    baud_rate: 9600

# Sensors
sensor:
  - platform: pm1006
    pm_2_5:
      name: ' '
    uart_id: uart_1
    
  - platform: mhz19
    co2:
      name: Carbon Dioxide
    temperature:
      name: Temperature
    update_interval: 120s
    automatic_baseline_calibration: false
    uart_id: uart_2
    
# Danger above 50% CO    
  - platform: adc
    pin: A0
    name: Carbon Monoxide
    update_interval: 60s
    filters:
      - lambda: return (x * 1024/5);
    unit_of_measurement: "ppm"
    icon: mdi:gas-cylinder #mdi:fire
