
binary_sensor:
  - platform: status
    name: Online
    id: system_status # sniffer only uses this

sensor:
  - platform: wifi_signal
    name: RSSI
    update_interval: 5s
    accuracy_decimals: 1
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
