
binary_sensor:
  - platform: status
    name: status
    id: system_status # sniffer only uses this

sensor:
  - platform: wifi_signal
    name: wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1
