"""Metric naming and key normalization helpers for Halthy."""

from __future__ import annotations

import re

_METRIC_WORDS = tuple(
    sorted(
        {
            "active",
            "analysis",
            "apple",
            "asleep",
            "atrial",
            "average",
            "basal",
            "blood",
            "body",
            "breathing",
            "burned",
            "calorie",
            "change",
            "climbed",
            "core",
            "count",
            "cycling",
            "deep",
            "diastolic",
            "distance",
            "duration",
            "effort",
            "energy",
            "estimated",
            "exercise",
            "fat",
            "flights",
            "glucose",
            "ground",
            "heart",
            "height",
            "in",
            "lean",
            "mass",
            "max",
            "minutes",
            "oxygen",
            "percentage",
            "rate",
            "recovery",
            "rem",
            "respiratory",
            "resting",
            "running",
            "saturation",
            "score",
            "sdnn",
            "sleep",
            "sleeping",
            "speed",
            "stand",
            "steps",
            "stride",
            "systolic",
            "temperature",
            "time",
            "variability",
            "vertical",
            "vo2",
            "vo2max",
            "walking",
            "weight",
            "workout",
        },
        key=len,
        reverse=True,
    )
)

_FRIENDLY_TOKEN_EXPANSIONS = {
    "avg": "average",
    "bp": "blood pressure",
    "hr": "heart rate",
    "hrv": "heart rate variability",
    "rem": "rapid eye movement",
    "sdnn": "standard deviation of nn intervals",
    "spo2": "blood oxygen saturation",
    "uv": "ultraviolet",
    "vo2": "maximal oxygen uptake",
    "vo2max": "maximal oxygen uptake",
}

_FRIENDLY_KEY_OVERRIDES = {
    "last_full_sync": "last full sync",
    "last_update": "last update",
    "oxygen_saturation": "blood oxygen",
    "blood_oxygen_saturation": "blood oxygen",
    "blood_oxygen": "blood oxygen",
    "sleep_score": "sleep efficiency estimated",
    "vo2_max": "maximal oxygen uptake",
    "vo2max": "maximal oxygen uptake",
    "walking_hr_avg": "walking heart rate average",
    "bp_systolic": "blood pressure systolic",
    "bp_diastolic": "blood pressure diastolic",
    "workout_route_start": "workout start",
    "workout_route_end": "workout end",
    "workout_route_map": "workout",
    "workout": "workout",
}

_METRIC_PREFIX_PATTERNS = (
    re.compile(
        r"^HK(?:Quantity|Category|Characteristic|Correlation|Document|Series|Data)TypeIdentifier",
        re.IGNORECASE,
    ),
    re.compile(r"^HKWorkoutTypeIdentifier", re.IGNORECASE),
    re.compile(r"^HKObjectTypeIdentifier", re.IGNORECASE),
)

_METRIC_KEY_ALIASES = {
    "sleep_in_g_wrist_temperature": "sleeping_wrist_temperature",
    "workout_route_map": "workout",
}

_NON_SELECTION_MANAGED_METRIC_KEYS: frozenset[str] = frozenset(
    {
        "last_full_sync",
        "last_update",
        "daily_upload_count",
        # Derived workout entities are generated by integration logic and may not
        # be present in the app's selected_metric_keys payload.
        "workout_start",
        "workout_end",
        "workout_route_start",
        "workout_route_end",
        "workout_route_map",
        "workout",
    }
)


def sanitize_identifier(value: str) -> str:
    cleaned = re.sub(r"[^a-z0-9_]+", "_", value.lower()).strip("_")
    return cleaned or "unknown"


def _strip_metric_prefix(metric_key: str) -> str:
    normalized = metric_key.strip()
    for pattern in _METRIC_PREFIX_PATTERNS:
        normalized = pattern.sub("", normalized, count=1)
    return normalized.strip() or metric_key.strip()


def _split_compound_word(part: str) -> list[str]:
    words: list[str] = []
    idx = 0
    while idx < len(part):
        match = next((word for word in _METRIC_WORDS if part.startswith(word, idx)), None)
        if match is not None:
            words.append(match)
            idx += len(match)
            continue

        next_idx = idx + 1
        while next_idx < len(part):
            if any(part.startswith(word, next_idx) for word in _METRIC_WORDS):
                break
            next_idx += 1
        words.append(part[idx:next_idx])
        idx = next_idx
    return words


def _tokenize_metric_key(metric_key: str) -> list[str]:
    prepared = _strip_metric_prefix(metric_key)
    prepared = re.sub(r"([a-z0-9])([A-Z])", r"\1 \2", prepared)
    prepared = re.sub(r"[^a-zA-Z0-9]+", " ", prepared).strip()
    if not prepared:
        return []

    tokens: list[str] = []
    for chunk in prepared.split():
        lowered = chunk.lower()
        if lowered.isalpha() and len(lowered) >= 6:
            tokens.extend(_split_compound_word(lowered))
        else:
            tokens.append(lowered)
    return [token for token in tokens if token]


def _sentence_case(text: str) -> str:
    compact = re.sub(r"\s+", " ", text).strip().lower()
    if not compact:
        return "Metric"
    return compact.capitalize()


def normalize_metric_key(metric_key: str) -> str:
    tokens = _tokenize_metric_key(metric_key)
    if not tokens:
        normalized = sanitize_identifier(metric_key)
        return _METRIC_KEY_ALIASES.get(normalized, normalized)

    while tokens and tokens[0] == "apple":
        tokens.pop(0)

    if not tokens:
        normalized = sanitize_identifier(metric_key)
        return _METRIC_KEY_ALIASES.get(normalized, normalized)

    normalized = sanitize_identifier("_".join(tokens))
    return _METRIC_KEY_ALIASES.get(normalized, normalized)


def friendly_metric_name(metric_key: str, provided_name: str | None) -> str:
    normalized_metric_key = normalize_metric_key(metric_key)
    override = _FRIENDLY_KEY_OVERRIDES.get(normalized_metric_key)
    if override is not None:
        return _sentence_case(override)

    tokens = _tokenize_metric_key(normalized_metric_key)
    while tokens and tokens[0] == "apple":
        tokens.pop(0)
    if not tokens:
        return _sentence_case(provided_name or "")

    rendered: list[str] = []
    for token in tokens:
        expanded = _FRIENDLY_TOKEN_EXPANSIONS.get(token)
        if expanded:
            rendered.extend(expanded.split())
        else:
            rendered.append(token)

    deduped: list[str] = []
    for token in rendered:
        if deduped and deduped[-1] == token:
            continue
        deduped.append(token)

    return _sentence_case(" ".join(deduped))


def metric_icon(metric_key: str, provided_icon: str | None) -> str:
    icon = (provided_icon or "").strip()
    if icon:
        return icon

    key = sanitize_identifier(metric_key)
    if any(token in key for token in ("sleep", "asleep", "in_bed")):
        return "mdi:sleep"
    if any(token in key for token in ("heart", "atrial", "pulse", "hrv", "sdnn")):
        return "mdi:heart-pulse"
    if any(token in key for token in ("walking", "running", "speed")):
        return "mdi:speedometer"
    if any(token in key for token in ("distance", "step", "steps")):
        return "mdi:map-marker-distance"
    if any(token in key for token in ("workout", "exercise", "move", "stand")):
        return "mdi:run-fast"
    if any(token in key for token in ("energy", "calorie", "burned")):
        return "mdi:fire"
    if any(token in key for token in ("blood_pressure", "systolic", "diastolic")):
        return "mdi:gauge"
    if any(token in key for token in ("oxygen", "spo2", "respiratory", "breathing")):
        return "mdi:lungs"
    if any(token in key for token in ("weight", "mass", "body_fat", "lean")):
        return "mdi:scale-bathroom"
    if "flight" in key:
        return "mdi:stairs"
    if "temperature" in key:
        return "mdi:thermometer"
    return "mdi:chart-line"


def is_selection_managed_metric(metric_key: str) -> bool:
    """Return True when the metric participates in selected-metrics pruning."""
    normalized = normalize_metric_key(metric_key)
    return normalized not in _NON_SELECTION_MANAGED_METRIC_KEYS
