#########################################################
#                                                                                                              #
#             Living Room Air Conditioning                                                            #
#                                                                                                              #
#########################################################


- alias: 'LR Room Aircon'
  initial_state: true
  trigger:
    platform: state
    entity_id: input_select.lr_ac_mode
  action:
  - service_template: >
      {% if is_state('input_select.lr_ac_mode', 'Powerful Heat') %} script.lr_ac_powerful_heat
      {% elif is_state('input_select.lr_ac_mode', 'Normal Heat') %} script.lr_ac_normal_heat
      {% elif is_state('input_select.lr_ac_mode', 'Silent Heat') %} script.lr_ac_silent_heat
      {% elif is_state('input_select.lr_ac_mode', 'Powerful Cool') %} script.lr_ac_powerful_cool
      {% elif is_state('input_select.lr_ac_mode', 'Normal Cool') %} script.lr_ac_normal_cool
      {% elif is_state('input_select.lr_ac_mode', 'Silent Cool') %} script.lr_ac_silent_cool
      {% elif is_state('input_select.lr_ac_mode', 'Normal Humidifier') %} script.lr_ac_normal_humidifier
      {% elif is_state('input_select.lr_ac_mode', 'Ai Auto') %} script.lr_ac_ai
      {% elif is_state('input_select.lr_ac_mode', 'Fan') %} script.lr_ac_fan
      {% elif is_state('input_select.lr_ac_mode', 'Off') %} script.lr_ac_off
      {% endif %}

#########################################################
#                                                                                                              #
#             AM Schedule Auto Timer                                                                 #
#                                                                                                              #
#########################################################

- alias: 'LR Aircon AM Schedule'
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.lr_ac_am_automation_time_active # AM on time trigger (only if temperature condition below is met)
      - binary_sensor.lr_ac_heat_required # also trigger if heating becomes required (only during time condition below)
      - binary_sensor.lr_ac_cool_required # also trigger if cooling becomes required (only during time condition below)
    to: 'on'
    for:
      seconds: 10 #(prevents start up glitches).
  - platform: state
    entity_id: binary_sensor.hallway_door # ac turns off when door is open
    to: 'off'
  condition:
  - condition: template # Vacation mode is not On
    value_template: "{{ not is_state('input_boolean.vacation_mode', 'on') }}}"
  - condition: state # Only if AC is off (prevents oscillation between heat and cool mode if temperature over/undershoots set point)
    entity_id: input_select.lr_ac_mode
    state: 'Off'
  - condition: state # only if hallway door is closed
    entity_id: binary_sensor.hallway_door
    state: 'off'
  - condition: or # And only if room heating or cooling is required (for the case of a time trigger)
    conditions:
    - condition: state
      entity_id: binary_sensor.lr_ac_heat_required
      state: 'on'
    - condition: state
      entity_id: binary_sensor.lr_ac_cool_required
      state: 'on'
  - condition: state # And only if current time is within AM automation time range (for the case of a temperature trigger)
    entity_id: binary_sensor.lr_ac_am_automation_time_active
    state: 'on'
  - condition: template # Someone is home
    value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.lr_ac_mode
      option: >
        {% if is_state('binary_sensor.lr_ac_heat_required', 'on') %}
          Normal Heat
        {% elif is_state('binary_sensor.lr_ac_cool_required', 'on') %}
          Normal Cool
        {% else %}
          'Off'
        {% endif %}

#########################################################
#                                                                                                              #
#             PM Schedule Auto Timer                                                                 #
#                                                                                                              #
#########################################################

- alias: 'LR Aircon PM Schedule'
  trigger:
  - platform: state
    entity_id:
      - binary_sensor.lr_ac_pm_automation_time_active # PM on time trigger (only if temperature condition below is met)
      - binary_sensor.lr_ac_heat_required # also trigger if heating becomes required (only during time condition below)
      - binary_sensor.lr_ac_cool_required # also trigger if cooling becomes required (only during time condition below)
    to: 'on'
    for:
      seconds: 10 #(prevents start up glitches).
  - platform: state
    entity_id: binary_sensor.hallway_door # if door is closed
    to: 'off'
  condition:
  - condition: template # Vacation mode is not On
    value_template: "{{ not is_state('input_boolean.vacation_mode', 'on') }}"
  - condition: state # Only if AC is off (prevents oscillation between heat and cool mode if temperature over/undershoots set point)
    entity_id: input_select.lr_ac_mode
    state: 'Off'
  - condition: state # only if hallway door is closed
    entity_id: binary_sensor.hallway_door
    state: 'off'
  - condition: or # And only if room heating or cooling is required (for the case of a time trigger)
    conditions:
    - condition: state
      entity_id: binary_sensor.lr_ac_heat_required
      state: 'on'
    - condition: state
      entity_id: binary_sensor.lr_ac_cool_required
      state: 'on'
  - condition: state # And only if current time is within PM automation time range (for the case of a temperature trigger)
    entity_id: binary_sensor.lr_ac_pm_automation_time_active
    state: 'on'
  - condition: template # Someone is home
    value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    service: input_select.select_option
    data_template:
      entity_id: input_select.lr_ac_mode
      option: >
        {% if is_state('binary_sensor.lr_ac_heat_required', 'on') %}
          Normal Heat
        {% elif is_state('binary_sensor.lr_ac_cool_required', 'on') %}
          Normal Cool
        {% else %}
          'Off'
        {% endif %}

#########################################################
#                                                                                                              #
#             Turn Aircon Off At Time                                                                  #
#                                                                                                              #
#########################################################

- alias: 'LR Aircon AM Off'
  initial_state: true
  trigger:
    platform: state # AM off time trigger
    entity_id:
      - binary_sensor.lr_ac_am_automation_time_active
    to: 'off'
  condition:
  - condition: state # Only if AM Automation is enabled
    entity_id: automation.lr_aircon_am_schedule
    state: 'on'
  - condition: template # And only if AC is on
    value_template: '{{ states("input_select.lr_ac_mode") != "Off" }}'
  - condition: template # Someone is home
    value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.lr_ac_mode
      option: 'Off'

- alias: 'LR Aircon PM Off'
  initial_state: true
  trigger:
    platform: state # PM off time trigger
    entity_id:
      - binary_sensor.lr_ac_pm_automation_time_active
    to: 'off'
  condition:
  - condition: state # Only if PM Automation is enabled
    entity_id: automation.lr_aircon_pm_schedule
    state: 'on'
  - condition: template # And only if AC is on
    value_template: '{{ states("input_select.lr_ac_mode") != "Off" }}'
  - condition: template # Someone is home
    value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.lr_ac_mode
      option: 'Off'

#########################################################
#                                                                                                              #
#             Manual Adjust Temperature                                                             #
#                                                                                                              #
#########################################################

- alias: 'LR Room Aircon Cool Temperature Adjust'
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.lr_ac_temp_set_cool
  condition:
    condition: template # If currently running a cool mode
    value_template: "{{ 'Cool' in states.input_select.lr_ac_mode.state }}"
  action:
    service_template: >
      {% if is_state('input_select.lr_ac_mode', 'Powerful Cool') %} script.lr_ac_powerful_cool
      {% elif is_state('input_select.lr_ac_mode', 'Normal Cool') %} script.lr_ac_normal_cool
      {% elif is_state('input_select.lr_ac_mode', 'Silent Cool') %} script.lr_ac_silent_cool
      {% endif %}

- alias: 'LR Room Aircon Heat Temperature Adjust'
  initial_state: true
  trigger:
    platform: state
    entity_id: input_number.lr_ac_temp_set_heat
  condition:
    condition: template # If currently running a heat mode
    value_template: "{{ 'Heat' in states.input_select.lr_ac_mode.state }}"
  action:
    service_template: >
      {% if is_state('input_select.lr_ac_mode', 'Powerful Heat') %} script.lr_ac_powerful_heat
      {% elif is_state('input_select.lr_ac_mode', 'Normal Heat') %} script.lr_ac_normal_heat
      {% elif is_state('input_select.lr_ac_mode', 'Silent Heat') %} script.lr_ac_silent_heat
      {% endif %}


#########################################################
#                                                                                                              #
#             Powerful Cool On                                                                           #
#                                                                                                              #
#########################################################


- alias: 'LR Powerful Cool On'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.lr_ac_mode
    to: 'Normal Cool'
    for:
      minutes: 30
  - platform: state
    entity_id: binary_sensor.lr_ac_cool_required
    to: 'on'
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: binary_sensor.lr_ac_cool_required
    state: 'on'
  - condition: state
    entity_id: input_select.lr_ac_mode
    state: 'Normal Cool'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.lr_ac_mode
      option: "Powerful Cool"

- alias: 'LR Powerful Cool Off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.lr_ac_mode
    to: 'Powerful Cool'
    for:
      minutes: 30
  - platform: state
    entity_id: binary_sensor.lr_ac_cool_required
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_select.lr_ac_mode
    state: 'Powerful Cool'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.lr_ac_mode
      option: "Normal Cool"

#########################################################
#                                                                                                              #
#             Powerful Heat On                                                                          #
#                                                                                                              #
#########################################################

- alias: 'LR Powerful Heat Off'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.lr_ac_mode
    to: 'Powerful Heat'
    for:
      minutes: 30
  - platform: state
    entity_id: binary_sensor.lr_ac_heat_required
    to: 'off'
    for:
      minutes: 5
  condition:
    condition: state
    entity_id: input_select.lr_ac_mode
    state: 'Powerful Heat'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.lr_ac_mode
      option: "Normal Heat"

- alias: 'LR Powerful Heat On'
  initial_state: true
  trigger:
  - platform: state
    entity_id: input_select.lr_ac_mode
    to: 'Normal Heat'
    for:
      minutes: 30
  - platform: state
    entity_id: binary_sensor.lr_ac_heat_required
    to: 'on'
    for:
      minutes: 5
  condition:
  - condition: state
    entity_id: binary_sensor.lr_ac_heat_required
    state: 'on'
  - condition: state
    entity_id: input_select.lr_ac_mode
    state: 'Normal Heat'
  action:
    service: input_select.select_option
    data:
      entity_id: input_select.lr_ac_mode
      option: "Powerful Heat"

#########################################################
#                                                                                                              #
#             Auto Set AM Living Room Heating Set Point                                        #
#                                                                                                              #
#########################################################

- alias: 'LR Heating Seasonal Adjustment AM'
  initial_state: true
  trigger:
  - platform: time
    at: '04:00:00'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.lr_heater_heat_temp_set
      value: >
        {% if is_state('sensor.season', 'summer') %}
          18
        {% elif is_state('sensor.season', 'autumn') %}
          19
        {% elif is_state('sensor.season', 'winter') %}
          19
        {% elif is_state('sensor.season', 'spring') %}
          17
        {% endif %}
  - condition: template
    value_template: "{{ states('sensor.outside_temperature')|float > 22 }}"
  - service: input_number.set_value
    data:
      entity_id: input_number.lr_heater_heat_temp_set
      value: 16


#########################################################
#                                                                                                              #
#             Auto Set PM Living Room Heating Set Point                                        #
#                                                                                                              #
#########################################################


- alias: 'LR Heating Seasonal Adjustment PM'
  initial_state: true
  trigger:
  - platform: time
    at: '13:00:00'
  action:
  - service: input_number.set_value
    data_template:
      entity_id: input_number.lr_heater_heat_temp_set
      value: >
        {% if is_state('sensor.season', 'summer') %}
          18
        {% elif is_state('sensor.season', 'autumn') %}
          19
        {% elif is_state('sensor.season', 'winter') %}
          19
        {% elif is_state('sensor.season', 'spring') %}
          17
        {% endif %}



#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################