#########################################################
#                                                                                                              #
#             Announcements                                                                            #
#                                                                                                              #
#########################################################

# Alexa Remind Shion to Go to Bed Starting at 9pm
- alias: Bedtime Start Announcements
  trigger:
    - platform: time
      at: '21:00:00'
  action:
    - service: timer.start
      entity_id: timer.looper
###
- alias: Bedtime Stop Announcements
  trigger:
    - entity_id: group.bed_sensors
      for: '00:00:30'
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '22:30:00'
  action:
    - service: timer.finish
      entity_id: timer.looper

- alias: 'Looper timer started'
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.looper
  action:
    service_template: >
       {% if now().hour > 21 %}
          timer.cancel
       {% else %}
          script.turn_on
       {% endif %}
    data_template:
      entity_id: >
        {% if now().hour > 21 %}
           timer.looper
        {% else %}
           script.bedtime_notify
        {% endif %}

- alias: 'Looper timer finished'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.looper
  condition:
    - condition: state
      entity_id: group.bed_sensors
      state: 'off'
  action:
    - service: timer.start
      entity_id: timer.looper



#########################################################
#                                                                                                              
#             Alexa Announce Who is Coming Home                                                 
#                                                                                                              
#########################################################

- alias: announce who is arriving
  trigger:
    - platform: state
      entity_id: 
#        - binary_sensor.duc_home # using apple tv
#        - binary_sensor.eri_home # using apple tv
        - device_tracker.duc
        - device_tracker.eri
#      to: 'on'
      to: 'home'
  action:
    - service: script.speech_engine
      data: 
        who: ai_1
        message:  >
          {% set alias = {"Eri":"mommy", "Duc":"daddy", "Shion":"she-on"} %}
          {% set p = trigger.to_state.attributes.friendly_name %}
          {% set person = alias.get(p) %}
          {{ person }}, will be home in about 10 minutes.

#    - condition: state
#      entity_id: light.h_1
#      state: 'off'
    - service: light.turn_on
      entity_id: light.h_1
      data:
        brightness: 200
    - delay: '00:10:00'
    - service: light.turn_off
      entity_id: light.h_1

#########################################################
#                                                                                                              #
#             Momentary Switch Trigger                                                               #
#                                                                                                              #
#########################################################


- alias: Momentary Switch Trigger
  trigger:
     - platform: state
       entity_id:
        - input_boolean.toggle_guest_presence   
        - binary_sensor.duc_presence
       to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: >-
          {% if is_state('input_boolean.toggle_guest_presence', 'on') %}
             switch.momentary_activate_guest
          {% elif is_state('binary_sensor.duc_presence', 'on') %}
             switch.momentary_activate_tv
          {% endif %}
    - delay: 2
    - condition: template 
      value_template: "{{ is_state('input_boolean.toggle_guest_presence', 'off') }}" 
    - service: homeassistant.turn_off
      data:
        entity_id: input_boolean.toggle_guest_presence 
    

#########################################################
#                                                                                                              
#             Alexa Greets Faimly at Genkan                                                                  
#                                                                                                              
#########################################################

- alias: welcome family announcement
  trigger:
    - platform: state
      entity_id:
       - binary_sensor.duc_presence
       - binary_sensor.eri_presence
       - binary_sensor.shion_presence
      to: 'on'
  action:
    - delay: 1
    - wait_template: "{{ is_state('binary_sensor.motion_g1_occupancy', 'on') }}"
      continue_on_timeout: false
      timeout: 10
    - service: script.speech_engine
      data: 
        who: ai_2
        message: !include ../tpl/speech/family_greetings.yaml

    - condition: template 
      value_template: "{{ not is_state('switch.momentary_activate_guest', 'on') }}" 
    - condition: template 
      value_template: "{{ states.sensor.front_illuminance.state | float > 0.22 }}" 
    - service: script.turn_on_lr_lights




#########################################################
#                                                                                                              
#             Alexa Greets Guest at Genkan                                                                  
#                                                                                                              
#########################################################

- alias: welcome guest announcement
  trigger:
    - platform: state
      entity_id:
       - binary_sensor.sachiko_presence
       - binary_sensor.tomokun_presence       
      to: 'on'
  action:
    - delay: 1
    - wait_template: "{{ is_state('binary_sensor.motion_g1_occupancy', 'on') }}"
      continue_on_timeout: false
      timeout: 10
    - service: script.speech_engine
      data: 
        who: ai_2
        message: !include ../tpl/speech/guest_greetings.yaml



#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################