#########################################################
#                                                                                                              #
#             Announcements                                                                            #
#                                                                                                              #
#########################################################

# Alexa Remind Shion to Go to Bed Starting at 9pm
- alias: Bedtime Start Announcements
  trigger:
    - platform: time
      at: '21:00:00'
  action:
    - service: timer.start
      entity_id: timer.looper
###
- alias: Bedtime Stop Announcements
  trigger:
    - entity_id: group.bed_sensors
      for: '00:01:30'
      from: 'off'
      platform: state
      to: 'on'
  condition:
    - condition: time
      after: '21:00:00'
      before: '22:30:00'
  action:
    - service: timer.finish
      entity_id: timer.looper

- alias: 'Looper timer started'
  trigger:
    - platform: event
      event_type: timer.started
      event_data:
        entity_id: timer.looper
  action:
    service_template: >
       {% if now().hour > 21 %}
          timer.cancel
       {% else %}
          script.turn_on
       {% endif %}
    data_template:
      entity_id: >
        {% if now().hour > 21 %}
           timer.looper
        {% else %}
           script.bedtime_notify
        {% endif %}

- alias: 'Looper timer finished'
  trigger:
    - platform: event
      event_type: timer.finished
      event_data:
        entity_id: timer.looper
  condition:
    - condition: state
      entity_id: group.bed_sensors
      state: 'off'
  action:
    - service: timer.start
      entity_id: timer.looper



#########################################################
#                                                                                                              #
#             Alexa Announce Who is Coming Home                                                 #
#                                                                                                              #
#########################################################

- alias: announce who is arriving
  trigger:
    - platform: state
      entity_id: 
#        - binary_sensor.duc_home
#        - binary_sensor.eri_home
        - device_tracker.duc
        - device_tracker.eri
#      to: 'on'
      to: 'home'
  action:
    - service: notify.alexa_media
      data_template:
        data:
          type: tts
        target:
         - media_player.ai_1
        message: >
         {% set alias = {"Eri":"mommy", "Duc":"daddy", "Shion":"she-on"} %}
         {% set p = trigger.to_state.attributes.friendly_name %}
         {% set person = alias.get(p) %}
         {{ person }}, will be home in about 10 minutes.

    - condition: state
      entity_id: light.h_1
      state: 'off'
    - service: light.turn_on
      entity_id: light.h_1
      data:
        brightness: 200

#########################################################
#                                                                                                              #
#             Momentary Switch Trigger                                                               #
#                                                                                                              #
#########################################################

- alias: Momentary Switch Trigger
  trigger:
     - platform: state
       entity_id:
        - group.guest_presence
        - binary_sensor.duc_presence
       to: 'on'
  action:
    - service: switch.turn_on
      data:
        entity_id: >-
          {% if is_state('binary_sensor.duc_presence', 'on') %}
             switch.momentary_activate_tv
          {% elif is_state('group.guest_presence', 'on') %}
             switch.momentary_activate_guest
          {% endif %}

#########################################################
#                                                                                                              #
#             Alexa Greets at Genkan                                                                  #
#                                                                                                              #
#########################################################

- alias: welcome home announcement
  trigger:
    - platform: state
      entity_id:
       - binary_sensor.duc_presence
       - binary_sensor.eri_presence
       - binary_sensor.shion_presence
       - binary_sensor.sachiko_presence
      to: 'on'
  action:
    - delay: 1
    - wait_template: "{{ is_state('binary_sensor.motion_g1_occupancy', 'on') }}"
      continue_on_timeout: false
      timeout: 10
    - service_template: >
           {% if is_state('switch.momentary_activate_guest', 'on') %}
              script.door_guest_greeting
           {% else %}
              script.door_family_greeting
           {% endif %}

      data:
        user: >
         {% set alias = {"Eri":"eddie", "Duc":"duck", "Shion":"she-on"} %}
         {% set p = trigger.to_state.attributes.friendly_name %}
         {% set user = alias.get(p) %}
         {{ user }}
    - condition: or
      conditions:
        - condition: template 
          value_template: "{{ states.sensor.period_of_the_day.state != 'daylight' }}" # Turn on LR lights
        - condition: time
          after: '17:45:00'
          before: '18:30:00'
    - service: script.turn_on_lr_lights


#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################