#########################################################
#                                                                                                              
#             Morning Email Briefings                                                                   
#                                                                                                              
#########################################################


- alias: "Morning Briefings"
  initial_state: true
  variables:
    msg: >-
      <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
      <br>
      <b> Today's Weather </b> <br>
      The current temperature is {{ states('sensor.wbio_current_temperature') }}° ( {{states('sensor.oa_feels_like')}}° feel like) with a forecast of {{ states('sensor.nws_overnight_forecast') }}. Today's low is {{ states('sensor.wbio_overnight_low') }}° with a high of {{ states('sensor.wbio_daytime_temperature') }}°. <br>
      The predicted precipitation today is{% if states.weather.weatherbit.attributes.forecast[0].precipitation == 0 %} 0mm. {% else %} {{ states.weather.weatherbit.attributes.forecast[0].precipitation }}mm at a chance of {{ states('sensor.wbio_current_rain_forecast') }}%. {% endif %} <br>
      <br>
      <b> Holidays & Birthdays </b> <br>
      {% if is_state('sensor.holiday', '') %} No Holidays or Birthdays Today {% else %}Today is {{ states('sensor.holiday') }}.{% endif %} <br>
      {% if is_state('sensor.holidaytomorrow', '') %} {% else %}Tomorrow is {{ states('sensor.holidaytomorrow') }}.{% endif %} <br>
      {% if is_state('sensor.holidayinaweek', '') %} {% else %} {{ states('sensor.holidayinaweek') }} is in one week.{% endif %}
      
      <b> A Picture of Us! </b>   
  trigger:
    - platform: time
      at: '06:00:00'
  action:
    - service: script.email_notify_image
      data:
        who: duc
        title: 'Morning Briefing'
        message: '{{ msg }}'
        path:
          - '/config/www/img/private/{{ range(1, 25) | random }}.jpg'
    - service: script.text_notify
      data:
        who: duc
        title: 'Weather'
        message: >-
          Currently {{state_attr('weather.weatherbit','temperature')}}°, 
          feels like {{states('sensor.oa_feels_like')}}°. 
          Today 
          {{ (state_attr('weather.weatherbit', 'forecast')
              | map(attribute="temperature")
              | list)[0:1]
              | max }}°
          /{{ state_attr('weather.weatherbit', 'forecast')[0].templow }}° 
          {{ states('weather.weatherbit') }} 
          humidity {{ state_attr('weather.weatherbit', 'humidity') }}% 
          with 
          {% if state_attr('weather.weatherbit', 'forecast')[0].precipitation_probability != 0 %}
             preciptation of {{ state_attr('weather.weatherbit', 'forecast')[0].precipitation }}
          {%else%}
             no precipitation
          {%endif%}.
   
    - service: script.email_notify_image
      data:
        who: eri
        title: 'Morning Briefing'
        message: '{{ msg }}'
        path:
          - '/config/www/img/private/{{ range(1, 25) | random }}.jpg'


#########################################################
#                                                                                                              
#             Morning Wakeup Report                                                                   
#                                                                                                              
#########################################################

- alias: 'Morning Wakeup Report'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_computerroom_occupancy
      to: 'on'
  condition:
    - condition: time
      after: '05:00:00'
      before: '06:00:00'
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: state
      entity_id: input_boolean.morning_wakeup_report
      state: 'off'
  action:
    - service: script.morning_wakeup_report
    - service: input_boolean.turn_on
      entity_id: input_boolean.morning_wakeup_report


#########################################################
#                                                                                                              
#             Morning Briefing                                                                   
#                                                                                                              
#########################################################

- alias: 'Morning Report'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_computerroom_occupancy
      to: 'on'
  condition:
    - condition: time
      after: '06:15:00'
      before: '08:30:00'
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: state
      entity_id: input_boolean.good_morning_report
      state: 'off'
  action:
    - service: script.morning_briefing
    - service: input_boolean.turn_on
      entity_id: input_boolean.good_morning_report


#########################################################
#                                                                                                              
#             Daily Briefing                                                                   
#                                                                                                              
#########################################################

- alias: 'Daily Report'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_computerroom_occupancy
      to: 'on'
  condition:
    - condition: time
      after: '12:00:00'
      before: '15:00:00'
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: state
      entity_id: input_boolean.daily_report
      state: 'off'
  action:
    - service: script.daily_briefing
    - service: input_boolean.turn_on
      entity_id: input_boolean.daily_report

#########################################################
#                                                                                                              
#             Nightly Briefing                                                                   
#                                                                                                              
#########################################################

- alias: 'Nightly Briefing'
  trigger:
    - platform: time
      at: input_datetime.nightly_briefing
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    - service: script.nightly_briefing


#########################################################
#                                                                                                              
#             Event Briefing                                                                   
#                                                                                                              
#########################################################

- alias: 'Event Briefing'
  trigger:
    - platform: time
      at: input_datetime.event_briefing
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    - service: script.event_briefing



#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################