#########################################################
#                                                                                                              
#              Tv Lock                                                                                      
#                                                                                                              
#########################################################


- alias: enable tv lock
  variables:
    digit: 5
  trigger:
    - platform: template
      value_template: '{{ states.sensor.time.state == states.input_datetime.tv_lock_time.state[0:5] }}'
  condition:
    - condition: template # Child mode is on
      value_template: "{{ is_state('input_boolean.child_mode', 'on') }}"
    - condition: template # Someone is home
      value_template: "{{ is_state('group.family_presence', 'on') }}"
  action:
    - service: script.speech_engine_simplified
      data: 
        who: notify.alexa_media
        device: media_player.ai_1
        message:  >
          <audio src='https://ha.snailmsg.com/local/alerts/en/minecraft-theme.mp3'/>.. The time is {{ now().hour }} {{ now().minute }}, The tv will shutoff in {{ digit }} minutes.
        
    - delay:
        minutes: "{{ digit }}"
    - condition: template # Child mode is on
      value_template: "{{ is_state('input_boolean.child_mode', 'on') }}"
    - service: switch.turn_on
      entity_id: switch.tv_lock


#########################################################
#                                                                                                              
#             Disable Internet on Devices                                                            
#                                                                                                              
#########################################################


- alias: disable iphone internet
  trigger:
    - platform: template
      value_template: "{{ states.sensor.time.state == states.sensor.disable_device_time.state[0:5] }}"
  action:
    - condition: template
      value_template: "{{ not is_state('switch.is_internet', 'on') or not is_state('switch.isp_internet', 'on') }}"
    - service: switch.turn_on
      entity_id: switch.is_internet, switch.isp_internet, switch.switch_internet


#########################################################
#                                                                                                              
#             Enable all Disabled Devices at Midnight                                              
#                                                                                                              
#########################################################

- alias: enable devices at midnight
  trigger:
    - platform: time
      at: '01:00:00'
  action:
    - service: script.enable_devices

#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################