#########################################################
#                                                                                                              
#             Ask to turn on ac if above 30C                                                         
#                                                                                                              
#########################################################

- alias: Skills Ask - Turn on LR Aircon
  triggers:
    - trigger: state
      entity_id: binary_sensor.duc_presence
      to: 'on'
      for: '00:00:30'
    - trigger: numeric_state
      entity_id: sensor.lr_radar_temperature
      above: input_number.lr_ac_cool_temp_set # 31 # input_number.lr_ac_cool_temp_set
      for: '00:00:20'
  conditions:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: template # LR aircon is off
      value_template: "{{ is_state('input_select.lr_ac_mode', 'Off') }}"
    - condition: template
      value_template: >- # LR Aircon cool settings
          {{ states('sensor.lr_radar_temperature') | float(default=24) > states('input_number.lr_ac_cool_temp_set') | float(default=25) }}
  actions:
    - action: script.activate_alexa_actionable_notification
      data:
        text: 'The current livingroom temperature is {{ states("sensor.lr_radar_temperature") }} degree celsius. Would you like me to turn on the livingroom AC?'
        event_id: 'ask_to_turn_on_lr_aircon'
        who: 'media_player.ai_1'

- alias: Skills Rsp - Turn on LR Aircon
  triggers:
    - trigger: event
      event_type: alexa_actionable_notification
      event_data:
        event_id: 'ask_to_turn_on_lr_aircon'
        event_response_type: ResponseYes
  actions:
    - action: switch.turn_on
      entity_id: switch.ac_lr_unit



#########################################################
#                                                                                                              
#          END OF CONFIGURATION FILE                                                             
#                                                                                                              
#########################################################