#########################################################
#                                                                                                              
#             Hallway Light                                                                                
#                                                                                                              
#########################################################

- alias: 'motion hallway auto-on'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_occupancy
      from: 'off'
      to: 'on'
  condition:
    - condition: template # Not on vacation
      value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"
  action:
    - service_template: script.hallway_light_guest_mode_{{ 'on' if is_state('input_boolean.guest_mode', 'on') else 'off' }}

- alias: 'motion hallway auto-off'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_hallway_occupancy
      to: 'off'
      for: '00:01:00'
  action:  
    - service: light.turn_off
      data:
        entity_id: light.h_2


#########################################################
#                                                                                                              
#             Genkan Light & LR only at night                                                       
#                                                                                                              
#########################################################

- alias: 'motion genkan auto-on'
  trigger:
   - platform: state
     entity_id: binary_sensor.motion_g1_occupancy
     to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.h_1
      data:
        brightness: 200

- alias: 'motion genkan auto-off'
  trigger:
  - platform: state
    entity_id: binary_sensor.motion_g1_occupancy
    to: 'off'
    for: '00:01:00'
  action:  
  - service: light.turn_off
    data:
      entity_id: light.h_1


#########################################################
#                                                                                                              
#             Turn on Genkan For Eri During Workdays                                            
#                                                                                                              
#########################################################

- alias: 'turn on genkan for eri'
  trigger:
    platform: time
    at: '06:18:00'
  condition:
  - condition: and
    conditions:
    - condition: template # Is weekday
      value_template: "{{ is_state('sensor.date_weekday', 'on') }}"
    - condition: template # Don't run if holiday
      value_template: "{{ states.sensor.holiday.state | trim == '' }}"

    - condition: state
      entity_id: binary_sensor.eri_presence
      state: 'on'
  action:
  - service: light.turn_on
    entity_id: light.h_1
    data:
      brightness: 200
#  - delay: 00:13
#  - service: light.turn_off
#    data:
#      entity_id: light.h_1


#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################