#########################################################
#                                                                                                              #
#             Open Front Curtains                                                                      #
#                                                                                                              #
#########################################################


- alias: 'Open Front Curtains at Sunrise'
  trigger:
    - entity_id: sensor.period_of_the_day
      platform: state
      to:
       - 'dawnlight'
       - 'daylight'
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    - service: cover.set_cover_position
      data:
        position: '{% if is_state("sensor.period_of_the_day", "dawnlight") %} 50 {% else %} 100 {% endif %}'
        entity_id:
        - cover.fr_curtains


#########################################################
#                                                                                                              #
#             Close Front Curtains                                                                      #
#                                                                                                              #
#########################################################


- alias: 'Close Front Curtains at Sunset'
  trigger:
    - entity_id: sensor.period_of_the_day
      platform: state
      to:
       - 'dusklight'
       - 'nightlight'
  condition:
    - condition: template 
      value_template: "{{ states('sensor.fr_curtains') != 'closed' }}"
  action:
    - service: cover.set_cover_position
      data:
        position: '{% if is_state("sensor.period_of_the_day", "dusklight") %} 50 {% else %} 0 {% endif %}'
        entity_id:
        - cover.fr_curtains

#########################################################
#                                                                                                              #
#             Automate Livingroom Lights via Photosensitivity                                  #
#                                                                                                              #
#########################################################

- alias: 'computer room lights on when dark'
  trigger:
    - platform: numeric_state
      entity_id: sensor.front_illuminance
      above: 0.21
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    - service_template: script.cr_lights_fadein_{{ 'day' if now().hour > 7 and now().hour < 16 else 'night' }}
      data:
        entity: computer_room

- alias: 'livingroom lights on when dark'
  trigger:
    - platform: numeric_state
      entity_id: sensor.front_illuminance
      above: 0.21
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: or
      conditions:
        - condition: template # Is the weekend or
          value_template: "{{ is_state('sensor.date_weekday', 'off') }}" 
        - condition: template # Is a holiday
          value_template: "{{ states('sensor.holiday')| trim != '' }}"
  action:
    - service_template: script.lr_lights_fadein_{{ 'day' if now().hour > 7 and now().hour < 16 else 'night' }}
      data:
        entity: living_room

- alias: 'front area lights off when bright'
  trigger:
    - platform: numeric_state
      entity_id: sensor.front_illuminance
      below: 0.18
  action:
    - service: light.turn_off
      entity_id:
       -  light.computer_room
       -  light.living_room


#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################