#########################################################
#                                                                                                              #
#             Open Front Curtains                                                                      #
#                                                                                                              #
#########################################################


- alias: 'Open Front Curtains at Sunrise'
  trigger:
    - entity_id: sensor.period_of_the_day
      platform: state
      to:
       - 'dawnlight'
       - 'daylight'
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    - service: cover.set_cover_position
      data:
        position: '{% if is_state("sensor.period_of_the_day", "dawnlight") %} 50 {% else %} 100 {% endif %}'
        entity_id:
        - cover.fr_curtains


#########################################################
#                                                                                                              #
#             Close Front Curtains                                                                      #
#                                                                                                              #
#########################################################


- alias: 'Close Front Curtains at Sunset'
  trigger:
    - entity_id: sensor.period_of_the_day
      platform: state
      to:
       - 'dusklight'
       - 'nightlight'
  condition:
    - condition: template 
      value_template: "{{ states('sensor.fr_curtains') != 'closed' }}"
  action:
    - service: cover.set_cover_position
      data:
        position: '{% if is_state("sensor.period_of_the_day", "dusklight") %} 50 {% else %} 0 {% endif %}'
        entity_id:
        - cover.fr_curtains


#########################################################
#                                                                                                              #
#             Motion Light Trigger                                                                      #
#                                                                                                              #
#########################################################
## TEST##

- alias: 'motion Livingroom Lights On'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sr_occupancy
      to: 'on'
  action:  
    - service: light.turn_on
      data:
        entity_id: light.l_2


- alias: 'motion Livingroom Lights Off'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_sr_occupancy
      to: 'off'
      for:
       seconds: 15     
  action:  
    - service: light.turn_off
      data:
        entity_id: light.l_2






#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################