#########################################################
#                                              
#             Open Front Curtains
#                                        
#########################################################

# CURRENTLY USING #
#- alias: 'Open Front Curtains at Sunrise'
#  trigger:
#    - entity_id: sensor.period_of_the_day
#      platform: state
#      to:
#       - 'dawnlight'
#       - 'daylight'
#  condition:
#    - condition: template # Someone is home
#      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
#    - condition: template # Not in Vacation
#      value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"
#  action:
#    - service: cover.set_cover_position
#      data:
#        position: '{% if is_state("sensor.period_of_the_day", "dawnlight") %} 50 {% else %} 100 {% endif %}'
#        entity_id:
#        - cover.fr_curtains


#########################################################
#                                                                                                              
#             Close Front Curtains
#                                                                                                              
#########################################################

# CURRENTLY USING #
#- alias: 'Close Front Curtains at Sunset'
#  trigger:
#    - entity_id: sensor.period_of_the_day
#      platform: state
#      to:
#       - 'dusklight'
#       - 'nightlight'
#  condition:
#    - condition: template 
#      value_template: "{{ states('sensor.fr_curtains') != 'closed' }}"
#    - condition: template # Not in Vacation
#      value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"      
#  action:
#    - service: cover.set_cover_position
#      data:
#        position: '{% if is_state("sensor.period_of_the_day", "dusklight") %} 50 {% else %} 0 {% endif %}'
#        entity_id:
#        - cover.fr_curtains

#########################################################
#                                                                                                              
#             Automate Front Area Lights via Photolight Sensor                                     
#                                                                                                              
#########################################################

- alias: 'computer room lights auto-on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.lr_radar_illuminance
      above: 0.38
      below: 0.51
  condition:  
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: template # Not in Vacation
      value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"
  action:
#    - service_template: script.cr_lights_fadein_{{ 'day' if now().hour > 7 and now().hour < 16 else 'night' }}
#      data:
#        entity: computer
    - service: script.tradfri_transition
      data:
        entity_id: light.computer
        color_temp: 143
        transition: "{{ (( states.input_number.wakeup_duration.state | float(0) * 60 * 2 )| round ) | int(0) }}"
        brightness: '{{ 151 if now().hour > 7 and now().hour < 16 else 254 }}'
#      entity_id: light.computer
  mode: restart


- alias: 'livingroom lights auto-on'
  trigger:
    - platform: numeric_state
      entity_id: sensor.lr_radar_illuminance
      above: 0.38
      below: 0.51
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: template # Not in Vacation
      value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"
    - condition: or # don't turn on weekdays
      conditions:
        - condition: template
          value_template: "{{ is_state('sensor.date_weekday', 'off') }}"
        - condition: template
          value_template: "{{ states('sensor.holiday')| trim != '' }}"
  action:
#    - service_template: script.lr_lights_fadein_{{ 'day' if now().hour > 7 and now().hour < 16 else 'night' }}
#      data:
#        entity: living
    - service: script.tradfri_transition
      data:
        entity_id: light.living
        color_temp: 143
        transition: "{{ (( states.input_number.wakeup_duration.state | float(0) * 60 * 2 )| round ) | int(0) }}"
        brightness: '{{ 151 if now().hour > 7 and now().hour < 16 else 254 }}'
#      entity_id: light.living
  mode: restart


- alias: 'front area lights auto-off'
  trigger:
    - platform: template
      value_template: "{{ states('sensor.lr_radar_illuminance') | float(0) < 0.29 and
                                 states('sensor.lr_radar_illuminance') != 'unavailable' and
                                 states('sensor.time') >= '06:00' }}"                      
    - platform: template
      value_template: "{{ states('sensor.lr_radar_illuminance') | float(0) < 0.29 and
                                 states('sensor.lr_radar_illuminance') != 'unavailable' }}"

  condition:      
    - condition: template  # If guest is present, do not turn off
      value_template: "{{ not is_state('input_boolean.guest_mode', 'on') }}"

  action:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ states('sensor.time') > '06:00' }}"
          sequence:
            - service: light.turn_off
              entity_id: light.computer, light.living
            - service: script.turn_off
              data_template:
                entity_id: script.tradfri_transition

        - conditions:
            - condition: template
              value_template: "{{ states('sensor.date_weekday') == 'off' }}"
          sequence:
            - service: light.turn_off
              entity_id: light.computer, light.living           
            - service: script.turn_off
              data_template:
                entity_id: script.tradfri_transition         
         
      default:
        - service: light.turn_off
          entity_id: light.computer
        - service: script.turn_off
          data_template:
            entity_id: script.tradfri_transition
  mode: restart
            

#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################