#########################################################
#                                                                                                              
#             Inventory Items Reminder                                                                 
#                                                                                                              
#########################################################

- alias: Notify about expiring inventory items
  trigger:
    - platform: numeric_state
      entity_id: sensor.items_expiring_soon
      above: 0
    - platform: time
      at: "06:00:00"
  condition:
    - condition: numeric_state
      entity_id: sensor.items_expiring_soon
      above: 0
  action:
    - service: notify.mobile_app_id
      data:
        title: "ðŸ—“ï¸ Inventory Items Expiring Soon"
        message: >
          {% set expiring = state_attr('sensor.items_expiring_soon', 'expiring_items') %}
          {% set expired = state_attr('sensor.items_expiring_soon', 'expired_items') %}
          {% if expired %}
            âš ï¸ {{ expired | length }} expired items: {{ expired[:3] | map(attribute='name') | join(', ') }}
          {% endif %}
          {% if expiring %}
            ðŸ“… {{ expiring | length }} expiring soon: {{ expiring[:3] | map(attribute='name') | join(', ') }}
          {% endif %}
        data:
          actions:
            - action: "view_inventory"
              title: "View Inventory"







#########################################################
#                                                                                                              
#             Maintenance Reminders                                                                  
#                                                                                                              
#########################################################


# Clean Aircon Filters Start of Season
# https://www.almanac.com/content/first-day-seasons
- alias: 'Clean Nozzle Filters'
  triggers:
    - trigger: state
      entity_id: sensor.season
  conditions:
  - condition: template # Not on Vacation
    value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"
  actions:
    - action: switch.toggle # Aircon Filters
      entity_id: group.clean_aircon_filter
    - action: script.toilet_nozzle_cleaning


#########################################################
#                                                                                                              
#            Turn on Shion Lights During School Days                                             
#                                                                                                              
#########################################################

# sensors located at sensors/wakeup.yaml
- alias: 'wakeup light bedroom'
  triggers:
    - trigger: template
      value_template: "{{ states('sensor.time') == states('sensor.wakeup_start_time_lights') }}"
  conditions:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: template
      value_template: "{{ states('sensor.holiday')| trim == 'none' }}"
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekends
          state: 'on'
        - condition: template # Is weekday
          value_template: "{{ is_state('sensor.date_weekday', 'on') }}"
  actions:
    - action: python_script.smooth_fader
      data:
        entity_id: "{{ states('sensor.wakeup_map') }}"
        duration: "00:{{ states('input_number.wakeup_duration')|int }}:00"
        brightness_start: "{{ states('input_number.brightness_start')|int }}"
        brightness_end: "{{ states('input_number.brightness_end')|int }}"
        brightness_curve: exp5
        temperature_curve: exp5


#########################################################
#                                                                                                              
#             Sensors that need a little push
#                                                                                                              
#########################################################

- alias: Daily Entity Refresh
  triggers:
    - trigger: time
      at: '17:00:00'
  actions:
    - action: homeassistant.update_entity
      entity_id: sensor.school_tomorrow

- alias: Good Night
  initial_state: true
  triggers:
    - trigger: time
      at: '22:15:00'
  actions:
    - action: script.turn_on
      entity_id: script.school_year_over
    - action: input_boolean.turn_off
      entity_id: input_boolean.school_today
    - action: input_boolean.turn_off
      entity_id: input_boolean.audible_notifications
    - action: input_boolean.turn_off
      entity_id: input_boolean.good_morning_report
    - action: input_boolean.turn_off
      entity_id: input_boolean.morning_wakeup_report
    - action: input_boolean.turn_off
      entity_id: input_boolean.daily_report
    - action: script.reset_earthquake_daily_count
    - action: input_boolean.turn_off
      entity_id: input_boolean.jcom_tv

    - action: script.text_notify_image
      data:
        who: amber
        image: >-
          {{ [ "/config/www/img/misc/off-01.jpg",
               "/config/www/img/misc/off-02.jpg",
               "/config/www/img/misc/off-03.jpg",
               "/config/www/img/misc/off-04.jpg"] | random }}
        caption: >-
          {{ [
          "Good Night from Lions Mansion. ",
          "Time to shut down this party. Good Night from Lions Mansion. ",
          "I'm feeling tired. Think I'll take a quick nap. Good Night!",
          "Things are getting quiet. Time to say Good Night.",
          "We have come to the end of our broadcast day. Oh, who am I kidding. I''ll be up all night watching over Lions Mansion. "
          ] | random }}


#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################