#########################################################
#                                                                                                              #
#             Maintenance Reminders                                                                  #
#                                                                                                              #
#########################################################


# Clean Aircon Filters Start of Season
# https://www.almanac.com/content/first-day-seasons                                          
- alias: 'Clean Nozzle Filters'
  trigger:
    platform: state
    entity_id: sensor.season
  condition:
  - condition: template # Not on Vacation
    value_template: "{{ not is_state('input_select.home_mode', 'Vacation') }}"
  action:
    - service: switch.turn_on # Aircon Filters
      entity_id: group.clean_aircon_filter
    - service: script.toilet_nozzle_cleaning


#########################################################
#                                                                                                              #
#            Turn on Shion Lights During School Days                                             #
#                                                                                                              #
#########################################################


- alias: 'wakeup light bedroom'
  trigger:
    platform: template
    value_template: '{{ states.sensor.time.state == states.sensor.wakeup_start_time_lights.state }}'
  condition:
    - condition: state
      entity_id: input_boolean.wakeup
      state: 'on'
    - condition: template
      value_template: "{{ states.sensor.holiday.state | trim == '' }}"
    - condition: or
      conditions:
        - condition: state
          entity_id: input_boolean.wakeup_weekends
          state: 'on'
        - condition: template # Is weekday
          value_template: "{{ is_state('sensor.date_weekday', 'on') }}"
  action:
    service: script.wakeup_bedroom


#########################################################
#                                                                                                              #
#             Sensors that need a little push                                                 
#                                                                                                              #
#########################################################

- alias: Daily Entity Refresh
  trigger:
  - platform: time
    at: '17:00:00'
  action:
    - service: homeassistant.update_entity
      entity_id: sensor.school_tomorrow

- alias: Good Night
  initial_state: true
  trigger:
    - platform: time
      at: '22:30:00'
  action:
    - service: script.turn_on
      entity_id: script.school_year_over
    - service: input_boolean.turn_off
      entity_id: input_boolean.school_today
    - service: input_boolean.turn_off
      entity_id: input_boolean.audible_notifications
    - service: input_boolean.turn_off
      entity_id: input_boolean.good_morning_report
    - service: input_boolean.turn_off
      entity_id: input_boolean.morning_wakeup_report
    - service: input_boolean.turn_off
      entity_id: input_boolean.daily_report        
    - service: script.reset_earthquake_one_day_count
    - service: script.enable_devices
    
    - service: script.text_notify
      data:
        who: duc
        message: >-
          {{ [ 
            "Good Night from Lions Mansion. ", 
            "Time to shut down this party. Good Night from Lions Mansion. ",
            "I'm feeling tired. Think I'll take a quick nap. Good Night!",
            "Things are getting quiet. Time to say Good Night.",
            "We have come to the end of our broadcast day. Oh, who am I kidding. I''ll be up all night watching over Lions Mansion. " 
            ] | random }}


#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################