#########################################################
#                                                                                                              #
#            Presence - Family                                                                          #
#                                                                                                              #
#########################################################

# Duc
- alias: Presence Duc On
  trigger:
    - platform: numeric_state
      entity_id: sensor.id_presence
      above: 10
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.duc_presence
- alias: Presence Duc Off
  trigger:
    - platform: numeric_state
      entity_id: sensor.id_presence
      below: 10
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.duc_presence

# Eri
- alias: Presence Eri On
  trigger:
    - platform: numeric_state
      entity_id: sensor.ie_presence
      above: 10
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.eri_presence
- alias: Presence Eri Off
  trigger:
    - platform: numeric_state
      entity_id: sensor.ie_presence
      below: 10
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.eri_presence

# Shion
- alias: Presence Shioin On
  trigger:
    - platform: numeric_state
      entity_id: sensor.tms_presence
      above: 10
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.shion_presence
- alias: Presence Shioin Off
  trigger:
    - platform: numeric_state
      entity_id: sensor.tms_presence
      below: 10
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.shion_presence

#########################################################
#                                                                                                              #
#            Presence - Guests                                                                         #
#                                                                                                              #
#########################################################


# Sachiko
- alias: Presence Sachiko On
  trigger:
    - platform: numeric_state
      entity_id: sensor.sachiko_presence
      above: 10
  action:
    - service: input_boolean.turn_on
      data:
        entity_id: input_boolean.sachiko_presence, input_boolean.toggle_guest_presence
- alias: Presence Sachiko Off
  trigger:
    - platform: numeric_state
      entity_id: sensor.sachiko_presence
      below: 10
  action:
    - service: input_boolean.turn_off
      data:
        entity_id: input_boolean.sachiko_presence


#########################################################
#                                                                                                              #
#            Arrival | Departure                                                                         #
#                                                                                                             #
#########################################################

- alias: Presence Scan Arrival
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_g2_occupancy
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state('binary_sensor.motion_g1_occupancy', 'off') }}"
  action:
    - service: mqtt.publish
      data_template:
        topic: monitor/scan/arrive

- alias: Presence Scan Departure
  trigger:
    - platform: state
      entity_id: binary_sensor.genkan_door
      to: 'on'
  condition:
    - condition: template
      value_template: "{{ is_state('binary_sensor.motion_hallway_occupancy', 'on') }}"
    - condition: template
      value_template: "{{ is_state('binary_sensor.motion_g1_occupancy', 'on') }}"
  action:
    - delay: '00:02:00'
    - service: mqtt.publish
      data_template:
        topic: monitor/scan/depart

#########################################################
#                                                                                                              #
#            Restart Monitor                                                                              #
#                                                                                                              #
#########################################################

- alias: Presence Restart Daily
  initial_state: 'on'
  trigger:
    - platform: time
      at: '04:01:00'
  action:
    - service: mqtt.publish
      data:
        topic: monitor/scan/restart
        payload: ''


#########################################################
#                                                                                                              #
#            Away|Home|Returning|Vacation status                                              #
#                                                                                                              #
#########################################################

# Home
- alias: Home Mode - Arriving
  trigger:
    - platform: state
      entity_id: sensor.n_people_home
  condition:
    - condition: template
      value_template: "{{ not is_state('input_boolean.vacation_mode', 'on') }}"
    - condition: template
      value_template: >
        {{ trigger.to_state.state|int > trigger.from_state.state|int }}
  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data:
        option: 'Home'

# Away
- alias: Home Mode - Leaving
  trigger:
    - platform: numeric_state
      entity_id: sensor.n_people_home
      below: 1
      for: 10
  condition:
    - condition: template
      value_template: "{{ not is_state('input_boolean.vacation_mode', 'on') }}"
    - condition: state
      entity_id: input_select.home_mode
      state: 'Home'
  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data:
        option: 'Away'
    - service: script.dev_check # turn off any devices that were left on
    - service: notify.mobile_app_id
      data:
        message: "There are {{ states('sensor.n_people_home') }} people at home now."
        title: '*Home Status*'

# Returning
- alias: Home Mode - Returning
  trigger:
    - platform: state
      entity_id: 
#        - binary_sensor.duc_home
#        - binary_sensor.eri_home
        - device_tracker.duc
        - device_tracker.eri
        - device_tracker.shion        
#      to: 'on'
      to: 'home'
  condition:
    - condition: template
      value_template: "{{ is_state('input_select.home_mode', 'Away') or is_state('input_select.home_mode', 'Vacation') }}"
  action:
    - service: input_select.select_option
      entity_id: input_select.home_mode
      data:
        option: 'Returning'

# Vacation
- alias: Home Mode - Vacation
  trigger:
  - platform: state
    entity_id: input_boolean.vacation_mode
  action:
    choose:
      - conditions: >
           {{ states.input_boolean.vacation_mode.state == 'on' }}
        sequence:
          - service: input_select.select_option
            entity_id: input_select.home_mode
            data:
              option: 'Vacation'
      - conditions: >
           {{ states.input_boolean.vacation_mode.state == 'off' and
              states.sensor.n_people_home.state | int  <= 2 }}
        sequence:
          - service: input_select.select_option
            entity_id: input_select.home_mode
            data:
              option: 'Away'
      - conditions: >
           {{ states.input_boolean.vacation_mode.state == 'off' and
              states.sensor.n_people_home.state | int  > 2 }}
        sequence:
          - service: input_select.select_option
            entity_id: input_select.home_mode
            data:
              option: 'Home'


#########################################################
#                                                                                                              #
#            Set Custom Device Tracker Location                                                  #
#                                                                                                              #
#########################################################

- alias: Set tms Tile Location
  trigger:
    - platform: state
      entity_id: input_boolean.shion_presence
  action:
    choose:
      - conditions: "{{ trigger.to_state.state == 'on' }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: shion
              location_name: "home"
              gps: 
              - '35.8182373046875'
              - '139.70377148641893'
      - conditions: "{{ trigger.to_state.state == 'off' }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: shion
              location_name: "not_home"
              gps: 
              - '00.0'
              - '000.0'

- alias: Set to work location waze
  trigger:
    - platform: numeric_state
      entity_id: sensor.duc_to_work_waze, sensor.eri_to_work_waze
      below: 3
  action:
    choose:
      - conditions: "{{ trigger.to_state.attributes.friendly_name == 'duc to work waze' }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: duc
              location_name: 'Duc Work'
              
      - conditions: "{{ trigger.to_state.attributes.friendly_name == 'eri to work waze' }}"
        sequence:
          - service: device_tracker.see
            data:
              dev_id: eri
              location_name: 'Eri Work'


#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################