#########################################################
#                                                                                                              #
#             Security Camera                                                                            #
#                                                                                                              #
#########################################################


- alias: 'Security Camera Snapshot'
  trigger:
    - platform: state
      entity_id: group.trigger_camera
      to: 'on'
  action:
    - delay: 10
    - service: camera.snapshot
      data:
        entity_id: camera.security
        filename: '/config/www/img/security/genkan_{{ now().strftime("%Y%m%d_%H%M%S") }}.jpg'


#########################################################
#                                                                                                              #
#             Alarm Triggered                                                                            #
#                                                                                                              #
#########################################################

- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id: 
       - binary_sensor.motion_mr_occupancy
       - binary_sensor.motion_lr_occupancy
      to: 'on'

  condition:
    - condition: template 
      value_template: "{{ is_state('alarm_control_panel.home_alarm', 'armed_away') }}"
  action:
    - service: script.alarm_light_flash

    - service: notify.home_assistant
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }} Alarm Triggered Notification"
        message: >
          <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
          <br>
          <b> Motion Alarm Triggered  </b> <br>
          The {{ trigger.to_state.attributes.friendly_name }} sensor has been triggered while no one is home.
          <br>
        data:
          images: []



- alias: 'Return Alarm to normal when alarm Disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: "disarmed"
  action:
    - service: script.returntonormal
      data:
        entity: light.ntl_1



########################
- alias: 'Count False Triggers'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_lr_occupancy
      to: 'on'
  condition:
    - condition: time 
      after: '22:00:00'
      before: '04:50:00'
  action:
    - service: notify.home_assistant
      data_template:
        title: "False Trigger Notification"
        message: >
          <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
          <br>
          <b> False Trigger  </b> <br>
          This email was send because the motion sensor detected false movement.
          <br>
        data:
          images: []

- alias: 'ESP8266 Offline Notification'
  trigger:
    - platform: state
      entity_id: binary_sensor.lr_sensor_dht_status
      to: 'off'
    - platform: state
      entity_id: binary_sensor.mr_dht_sensor_status
      to: 'off'
  action:
    - service: notify.home_assistant
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }} Offline"
        message: >
          <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
          <br>
          <b> ESP8266 Offline  </b> <br>
          This email was send because the {{ trigger.to_state.attributes.friendly_name }} sensor is offline.
          <br>
        data:
          images: []

########################





#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################