#########################################################
#                                                                                                              #
#             Security Camera                                                                            #
#                                                                                                              #
#########################################################


- alias: 'Security Camera Snapshot'
  trigger:
    - platform: state
      entity_id: group.trigger_camera
      to: 'on'
  action:
    - delay: 10
    - service: camera.snapshot
      data:
        entity_id: camera.security
        filename: '/config/www/img/security/genkan_{{ now().strftime("%Y%m%d_%H%M%S") }}.jpg'


#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################