#########################################################
#                                                                                                              #
#             Security Camera                                                                            #
#                                                                                                              #
#########################################################


- alias: 'Security Camera Snapshot'
  trigger:
    - platform: state
      entity_id: group.trigger_camera
      to: 'on'
  action:
    - delay: 10
    - service: camera.snapshot
      data:
        entity_id: camera.security
        filename: '/config/www/img/security/genkan_{{ now().strftime("%Y%m%d_%H%M%S") }}.jpg'


#########################################################
#                                                                                                              #
#             Livingroom Motion Triggered                                                            #
#                                                                                                              #
#########################################################

- alias: 'livingroom motion triggered'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_lr_occupancy
      to: 'on'
      for:
        seconds: 10
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Away') }}"
  action:
    - service: notify.home_assistant
      data_template:
        title: "House Motion Triggered"
        message: >
          <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
          <br>
          <b> Motion Triggered  </b> <br>
          Livingroom motion has been triggered and no one is home.
          <br>
        data:
          images: []

#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################