#########################################################
#                                                                                                              
#             Security Camera                                                                            
#                                                                                                              
#########################################################


#  - alias: 'Security MDF Camera Snapshot'
#    mode: queued
#    triggers:
#      - trigger: numeric_state
#        entity_id: sensor.mdf_illuminance
#        below: 0.55
#    actions:
#      - delay: 2
#      - action: camera.snapshot
#        data:
#          entity_id: camera.security_genkan
#          filename: '/config/www/img/security/{{ now().strftime("%Y%m%d_%H%M%S") }}security_mdf_camera.jpg'
#      - action: shell_command.clean_security_images



#########################################################
#                                                                                                              
#             Alarm Triggered                                                                            
#                                                                                                              
#########################################################

#- alias: 'Trigger alarm while armed away'
#  triggers:
#    - trigger: state
#      entity_id:
#       - binary_sensor.motion_lr_occupancy
#       - binary_sensor.mr_has_moving_target
#       - binary_sensor.sr_has_moving_target
#      to: 'on'
#  conditions:
#    - condition: template 
#      value_template: "{{ is_state('alarm_control_panel.home_alarm', 'armed_away') }}"
#  actions:
#    - action: script.alarm_light_flash
#
#    - action: notify.home_assistant
#      data:
#        title: "{{ trigger.to_state.attributes.friendly_name }} Alarm Triggered Notification"
#        message: >
#          <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
#          <br>
#          <b> Motion Alarm Triggered  </b> <br>
#          The {{ trigger.to_state.attributes.friendly_name }} sensor has been triggered while no one is home.
#          <br>
#        data:
#          images: []
#
#- alias: 'Return Alarm to normal when alarm Disarmed'
#  triggers:
#    - trigger: state
#      entity_id: alarm_control_panel.home_alarm
#      to: "disarmed"
#  actions:
#    - action: script.returntonormal
#      data:
#        entity: light.ntl_1
#


#########################################################
#                                                                                                              
#             Randomize Vacation Lights                                                                            
#                                                                                                              
#########################################################


- alias: Randomize Vacation Lights
  triggers:
  - trigger: state
    entity_id: input_boolean.randomize_vacation_lights
  conditions:
    - condition: state
      entity_id: input_boolean.vacation_mode
      state: 'on'
  actions: 
    - service_template: >
        {% if is_state('input_boolean.randomize_vacation_lights', 'on' )%} script.turn_on {% else %}
           script.turn_off
        {% endif %}
 
      data:
        entity_id: script.randomize_vacation_lights   

- alias: Run Vacation Lights
  triggers:
    - trigger: sun
      event: sunset
      id: sundown
    - trigger: sun
      event: sunrise
      id: sunup
    - trigger: state
      entity_id: input_boolean.vacation_mode
      id: cancel
      from: 'on'
      to: 'off'
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: sundown
            - condition: state
              entity_id: input_boolean.vacation_mode
              state: 'on'
          sequence:
            - action: input_boolean.turn_on
              entity_id: input_boolean.randomize_vacation_lights
        - conditions:
            - condition: or
              conditions:
              - condition: trigger
                id: sunup
              - condition: trigger
                id: cancel
          sequence:
            - action: input_boolean.turn_off
              entity_id: input_boolean.randomize_vacation_lights



#########################################################
#                                                                                                              
#          END OF CONFIGURATION FILE                                                             
#                                                                                                              
#########################################################