#########################################################
#                                                                                                              #
#             Security Camera                                                                            #
#                                                                                                              #
#########################################################


- alias: 'Security Camera Snapshot'
  trigger:
    - platform: state
      entity_id: binary_sensor.genkan_door
      to: 'on'
  action:
    - wait_template: "{{ is_state('light.h_1', 'on') }}"
      continue_on_timeout: false
      timeout: 10
    - delay: 1
    - service: camera.snapshot
      data:
        entity_id: camera.security
        filename: '/config/www/img/security/{{ now().strftime("%Y%m%d_%H%M%S") }}security_camera.jpg'
    - service: shell_command.clean_security_images


#########################################################
#                                                                                                              #
#             Alarm Triggered                                                                            #
#                                                                                                              #
#########################################################

- alias: 'Trigger alarm while armed away'
  trigger:
    - platform: state
      entity_id:
       - binary_sensor.motion_lr_occupancy
       - binary_sensor.motion_mr_occupancy
       - binary_sensor.motion_sr_occupancy
      to: 'on'
  condition:
    - condition: template 
      value_template: "{{ is_state('alarm_control_panel.home_alarm', 'armed_away') }}"
  action:
    - service: script.alarm_light_flash

    - service: notify.home_assistant
      data_template:
        title: "{{ trigger.to_state.attributes.friendly_name }} Alarm Triggered Notification"
        message: >
          <b>Today is {{ now().strftime( '%B %d, %Y') }} </b> <br>
          <br>
          <b> Motion Alarm Triggered  </b> <br>
          The {{ trigger.to_state.attributes.friendly_name }} sensor has been triggered while no one is home.
          <br>
        data:
          images: []

- alias: 'Return Alarm to normal when alarm Disarmed'
  trigger:
    - platform: state
      entity_id: alarm_control_panel.home_alarm
      to: "disarmed"
  action:
    - service: script.returntonormal
      data:
        entity: light.ntl_1


#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################