#########################################################
#                                                                                                              
#             Shelly EM Automation                                                                    
#                                                                                                              
#########################################################

- alias: 'Daily Energy Use Message'
  triggers:
    - trigger: time
      at: '23:59:50'
  actions:
    - action: script.text_notify
      data:
        who: whatsapp_duc
        title: '*Information*'
        message: "Today's energy use was {{ states('sensor.total_energy') }} kWh."
    - action: input_number.set_value
      data:
        entity_id: input_number.cumulative_energy_cost
        value: "{{ states('input_number.cumulative_energy_cost')|float(0) + states('sensor.total_cost_today')|float(0) }}"
    - action: notify.send_message
      target:
        entity_id: notify.energy_log
      data:
        message: "{{ states('sensor.date') }},{{ states('sensor.energy_t31_light_and_power_day') }},{{ states('sensor.energy_t31_light_and_power_night') }},{{ states('sensor.energy_t31_light_and_power_total') }},{{ states('sensor.energy_t41_heating_day') }},{{ states('sensor.energy_t41_heating_night') }},{{ states('sensor.energy_t41_heating_total') }},{{ states('sensor.total_energy_day') }},{{ states('sensor.total_energy_night') }},{{ states('sensor.total_energy') }},{{ state_attr('sensor.power_stats','age_coverage_ratio') }},{{ state_attr('sensor.power_stats','buffer_usage_ratio') }},{{ states('sensor.power_stats') }},{{ states('sensor.total_cost_today') }}"

- alias: 'Monthly Fridge Energy Use Message'
  triggers:
    - trigger: time
      at: '23:59:55'
  conditions:
    - condition: template
      value_template: "{{ now().day == 1 }}"
  actions:
    - action: notify.send_message
      target:
        entity_id: notify.fridge_log
      data:
        message: "{{ states('sensor.date') }},{{ states('sensor.energy_fridge_power_monthly') }}"

# Depreciate in 2024.12 
#    - action: notify.fridge_log
#      data:
#        message: "{{ states('sensor.date') }},{{ states('sensor.energy_fridge_power_monthly') }}"



#########################################################
#                                                                                                              
#             Switch Day Night Readings                                                              
#                                                                                                              
#########################################################


- alias: 'Set Dark Theme At Sunset'
  initial_state: true
  triggers:
    - trigger: sun
      event: sunset
  actions:
    - action: input_select.select_option
      data:
        entity_id: input_select.select_theme
        option: midnight
    - action: select.select_option ###### Tariff change to night from utility_meter.select_tariff 
      target:
        entity_id:
        - select.energy_t31_light_and_power
        - select.energy_t41_heating
      data:
        option: 'night'

- alias: 'Set Light Theme At Sunrise'
  initial_state: true
  triggers:
    - trigger: sun
      event: sunrise
  actions:
    - action: input_select.select_option
      data:
        entity_id: input_select.select_theme
        option: default_ha
    - action: select.select_option ###### Tariff change to day from utility_meter.select_tariff 
      target:
        entity_id:
        - select.energy_t31_light_and_power
        - select.energy_t41_heating
      data:
        option: 'day'

#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################