#########################################################
#                                                                                                              
#             Slack Actionable Notifications                                                          
#                                                                                                              
#########################################################

- alias: Slack - PC is on
  triggers:
    - trigger: state
      entity_id: binary_sensor.duc_presence
      to: 'off'
      for: 60
  conditions:
    - condition: template # PC left on
      value_template: "{{ is_state('binary_sensor.desktop_status', 'on') }}"
  actions:
    - action: script.notify_slack
      data:
        channel: !secret slack_channel_id
        message: "The PC was left {{ states('binary_sensor.desktop_status') }} and there are {{ states('sensor.n_people_home') }} person at home."
        attachments:
          - title: Turn off the PC?
            callback_id: turn_off_pc_callback
            color: '#03a9f4'
            attachment_type: default
            actions:
              - text: Turn off
                value: Turn off
                name: 'script.desktop_wol_off'
                type: button
              - text: Leave it
                value: Leave it
                name: 'dismiss'
                type: button

#########################################################
#                                                                                                              
#          END OF CONFIGURATION FILE                                                             
#                                                                                                              
#########################################################