#########################################################
#                                                                                                              #
#             Storage                                                                                       #
#                                                                                                              #
#########################################################


- alias: 'turn off storage room'
  trigger:
  - entity_id: light.storage_room
    platform: state
    to: 'on'
    for: '00:08:00'
  action:  
  - service: light.turn_off
    data:
      entity_id: light.str_1


#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################