#########################################################
#                                                                                                              #
#             Sunset Automations                                                                       #
#                                                                                                              #
#########################################################

- alias: 'computer room lights'
  trigger:
    - platform: sun
      event: sunset
      offset: -01:20:00
    - platform: sun
      event: sunset
      offset: -00:50:00
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
    - condition: template
      value_template: >-
        {{ trigger.offset.total_seconds()/60 == -50 or
           state_attr('weather.weatherbit_shimotoda', 'alt_condition')
           in ('cloudy', 'partlycloudy', 'rainy') }}
  action:
    - service: light.turn_on
      data:
        entity_id: light.computer_room
        transition: 600
        brightness_pct: 80



#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################