#########################################################
#                                                                                                              #
#             Telegram Actionable Notifications                                                     #
#                                                                                                              #
#########################################################

- alias: Telegram - PC is on
  trigger:
    platform: state
    entity_id: binary_sensor.duc_presence
    to: 'off'
    for: 60
  condition:
    - condition: template # PC left on
      value_template: "{{ is_state('binary_sensor.desktop_status', 'on') }}"

  action:
    - service: notify.amberthebot
      data_template:
        message: "The PC was left {{ states('binary_sensor.desktop_status') }} and there are {{ states('sensor.n_people_home') }} person at home."
        data:
          inline_keyboard:
          - 'Turn off pc:/turn_off_pc, Leave it:/donothing'

- alias: Telegram - Turn off PC
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: '/turn_off_pc'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK, turning off pc now'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []
    - service: script.desktop_shutdown


#########################################################
#                                                                                                              #
#             Global Callback                                                                             #
#                                                                                                              #
#########################################################

# Do Nothing
- alias: Telegram - Do Nothing
  trigger:
    - platform: event
      event_type: telegram_callback
      event_data:
        data: '/donothing'
  action:
    - service: telegram_bot.answer_callback_query
      data_template:
        callback_query_id: '{{ trigger.event.data.id }}'
        message: 'OK, no action taken'
    - service: telegram_bot.edit_replymarkup
      data_template:
        message_id: '{{ trigger.event.data.message.message_id }}'
        chat_id: '{{ trigger.event.data.chat_id }}'
        inline_keyboard: []


#########################################################
#                                                                                                              #
#             Controllable Devices                                                                       #
#                                                                                                              #
#########################################################

- alias: 'Control Devices'
  initial_state: 'on'
  trigger:
    platform: event
    event_type: telegram_text
  condition:
    condition: template
    value_template: >-
      {%- set text = trigger.event.data.text|lower -%}
      {%- set text = text.split(' ') -%}
      {%- if (text[0] == 'turn' or text[0] == 'switch') and (text[1] == 'on' or text[1] == 'off') -%}
      true
      {%- endif -%}
  action:
    - service: telegram_bot.send_message
      data_template:
        message: >-
          {%- set device = trigger.event.data.text|lower|replace('turn on ','')|replace('turn off ','')|replace('switch on ','')|replace('switch off ','') -%}
          {%- for entity in states.group.controllable_devices.attributes.entity_id if states[entity.split('.')[0]][entity.split('.')[1]].name|lower == device -%}
          OK, {{ trigger.event.data.text|lower|replace('turn','turning')|replace('switch','switching') }}.
          {%- else -%}
          I'm sorry. I cannot find the device named {{device}} in the house.
          {%- endfor -%}
        title: ''
        target: '{{ trigger.event.data.chat_id }}'
    - condition: template
      value_template: >-
        {%- set device = trigger.event.data.text|lower|replace('turn on ','')|replace('turn off ','')|replace('switch on ','')|replace('switch off ','') -%}
        {%- for entity in states.group.controllable_devices.attributes.entity_id if states[entity.split('.')[0]][entity.split('.')[1]].name|lower == device -%}
        true
        {%- else -%}
        false
        {%- endfor -%}
    - service_template: >-
        {%- set text = trigger.event.data.text|lower -%}
        {%- set text = text.split(' ') -%}
        {%- set onoff = text[1] -%}
        homeassistant.turn_{{onoff}}
      data_template:
        entity_id: >-
          {%- set device = trigger.event.data.text|lower|replace('turn on ','')|replace('turn off ','')|replace('switch on ','')|replace('switch off ','') -%}
          {%- for entity in states.group.controllable_devices.attributes.entity_id if states[entity.split('.')[0]][entity.split('.')[1]].name|lower == device -%}
          {{ entity }}
          {%- endfor -%}



#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################