#########################################################
#                                                                                                              #
#             Automate Light                                                                             #
#                                                                                                              #
#########################################################


- alias: 'motion toilet room auto-on'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_tr1_occupancy
    to: 'on'
  action:
    - service: light.turn_on
      entity_id: light.toilet
    - service: homeassistant.turn_on
      entity_id: input_boolean.engage_toilet_airfreshner

- alias: 'motion toilet room auto-off'
  trigger:
    platform: state
    entity_id: binary_sensor.motion_tr1_occupancy
    to: 'off'
    for: '00:02:00'
  action:
    - service: homeassistant.turn_off
      entity_id: input_boolean.engage_toilet_airfreshner
    - condition: template # If guest is present, do not turn off
      value_template: "{{not is_state('input_boolean.guest_mode', 'on') }}"
    - service: light.turn_off
      entity_id: light.toilet


#########################################################
#                                                                                                              #
#             Engage Toilet Air Freshner                                                               #
#                                                                                                              #
#########################################################

- alias: 'Engage Toilet Air freshner'
  trigger:
    platform: state
    entity_id: input_boolean.engage_toilet_airfreshner
    to: 'on'
    for: '00:04:00'
  condition:
    - condition: template # Someone is home
      value_template: "{{ is_state('input_select.home_mode', 'Home') }}"
  action:
    - service: switch.turn_on
      entity_id: switch.toilet_airfreshener
    - service: counter.increment
      target:
        entity_id: counter.toilet_airfreshner

#########################################################
#                                                                                                              #
#             Automate Heater                                                                          #
#                                                                                                              #
#########################################################

- alias: 'Enable Toilet Seat Heater'
  trigger:
    - platform: state
      entity_id: input_select.home_mode
  condition:
    - condition: template # Is not summer
      value_template: "{{ not is_state('sensor.season', 'summer') }}"
  action:
    choose:
      - conditions: "{{ trigger.to_state.state == 'Away' or trigger.to_state.state == 'Vacation' }}"
        sequence:
          - service: script.toilet_seat_off_heat
      - conditions: >
          {{ trigger.to_state.state == 'Home' or trigger.to_state.state == 'Returning' and 
             states('sensor.oa_temperature')| int <= 9}}
        sequence:
          - service: script.toilet_seat_high_heat
      - conditions: >
          {{ trigger.to_state.state == 'Home' or trigger.to_state.state == 'Returning' and 
             states('sensor.oa_temperature')| int <= 14 }}
        sequence:
          - service: script.toilet_seat_med_heat
      - conditions: >
          {{ trigger.to_state.state == 'Home' or trigger.to_state.state == 'Returning' and 
             states('sensor.oa_temperature')| int <= 19 }}
        sequence:
          - service: script.toilet_seat_low_heat
      - conditions: >
          {{ trigger.to_state.state == 'Home' or trigger.to_state.state == 'Returning' and 
             states('sensor.oa_temperature')| int >= 20 }}
        sequence:
          - service: script.toilet_seat_off_heat

#########################################################
#                                                                                                              #
#             Adjust Temperature Depending on OST                                             #
#                                                                                                              #
#########################################################

- alias: 'Adjust Toilet Seat Heater Temperature'
  trigger:
    - platform: state
      entity_id: sensor.oa_temperature
  condition:
    - condition: template # Is not summer
      value_template: "{{ not is_state('sensor.season', 'summer') }}"
  action:
    choose:
      - conditions: >
           {{ states.sensor.oa_temperature.state | int <= 9 and
              states.input_select.home_mode.state == 'Home' }}
        sequence:
          - service: script.toilet_seat_high_heat
      - conditions: >
           {{ states.sensor.oa_temperature.state | int <= 14 and
              states.input_select.home_mode.state == 'Home' }}
        sequence:
          - service: script.toilet_seat_med_heat
      - conditions: >
           {{ states.sensor.oa_temperature.state | int <= 19 and
              states.input_select.home_mode.state == 'Home' }}
        sequence:
          - service: script.toilet_seat_low_heat
#      - conditions: >
#           {{ states.sensor.oa_temperature.state | int <= 20 and
#              states.input_select.home_mode.state == 'Home' }}
#        sequence:
#          - service: script.toilet_seat_off_heat
      - conditions: >
           {{ states.sensor.oa_temperature.state | int >= 20 and
              states.input_select.home_mode.state == 'Home' }}
        sequence:
          - service: script.toilet_seat_off_heat
      - conditions: > # default to low if sensor not on
           {{ not is_state('binary_sensor.oa_dht_sensor_status', 'on') and
              states.input_select.home_mode.state == 'Home' }}
        sequence:
          - service: script.toilet_seat_low_heat

#########################################################
#                                                                                                              #
#             Hibernate Toilet Seat Heater                                                           #
#                                                                                                              #
#########################################################

- alias: 'Hibernate Toilet Seat Heater'
  trigger:
    - platform: state
      entity_id: sensor.season
      to: 'summer'
  action:
    - delay: 1
    - service: script.toilet_seat_off_heat

#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################