#########################################################
#                                                                                                              #
#             Waze Travel Time Destination Set                                                    #
#                                                                                                              #
#########################################################


- alias: 'Automate Duc Destination Waze'
  trigger:
  - platform: time
    at: '16:50:00'
  - platform: time
    at: '18:20:00'
    
  action:  
    choose:
      - conditions: "{{ now().hour == 16 and now().minute == 50 and is_state('binary_sensor.shion_at_school_baysn', 'on') }}"
        sequence:
          - service: input_select.select_option
            target:
              entity_id: input_select.duc_destination_waze
            data:
              option: school
              
    default:
      - service: input_select.select_option
        target:
          entity_id: input_select.duc_destination_waze
        data:
          option: jcb


#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################