#########################################################
#                                                                                                              #
#             Turn off TV                                                                                  #
#                                                                                                              #
#########################################################


- alias: turn off tv - weekdays
  trigger:
  - platform: time
    at: '20:59:00'
  condition:
  - condition: template # Child mode is on
    value_template: "{{ is_state('input_boolean.child_mode', 'on') }}"
  - condition: state
    entity_id: group.family_presence
    state: 'on'
  - condition: template # Is weekday
    value_template: "{{ is_state('sensor.date_weekday', 'on') }}"
  action:
    - service: notify.alexa_media
      data_template:
        data:
          type: tts
        target:
         - media_player.ai_1
        message: "<audio src='soundbank://soundlibrary/alarms/beeps_and_bloops/buzz_01'/>The tv will shutoff in 6 minutes."
    - delay: '00:06:00'
    - condition: template # Child mode is on
      value_template: "{{ is_state('input_boolean.child_mode', 'on') }}"
    - service: script.tv_source


#########################################################
#                                                                                                              #
#             END OF CONFIGURATION FILE                                                          #
#                                                                                                              #
#########################################################