#########################################################
#                                                                                                              #
#             Turn Off Lights If Left On                                                                #
#                                                                                                              #
#########################################################


- alias: 'turn off light after timeout'
  trigger:
#    - platform: state
#      entity_id:
#       - light.storage_room
#       - light.closet
#      to: 'on'
#      for:
#        minutes: 6

    - platform: state
      entity_id:
       - light.h_1
      to: 'on'
      for:
        minutes: 10
  action:
    - service: light.turn_off
      data_template:
        entity_id: "{{ trigger.entity_id }}"

- alias: 'motion master room closet auto-off'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_c1_occupancy
      to: 'off'
      for: '00:00:30'
  action:
    - service: light.turn_off
      entity_id: light.closet


- alias: 'motion pantry room auto-off'
  trigger:
    - platform: state
      entity_id: binary_sensor.motion_s1_occupancy
      to: 'off'
      for: '00:00:30'
  action:
    - service: light.turn_off
      entity_id: light.storage_room


#########################################################
#                                                                                                              #
#          END OF CONFIGURATION FILE                                                             #
#                                                                                                              #
#########################################################