#########################################################
#                                                                                                              
#             Washroom                                                                                   
#                                                                                                              
#########################################################

- alias: 'motion washroom auto-on'
  mode: parallel
  trigger:
#    - platform: state 
#      entity_id: group.motion_showerroom_occupancy
    - platform: template # alt if false positive occurs above
      value_template: |
       {%- set trig = (now() - states.binary_sensor.motion_washroom_sensor_occupancy.last_changed).seconds -%}
       {% if is_state('group.motion_showerroom_occupancy', 'on') and trig <= 300 %} true
       {% else %} false {% endif %}
    - platform: state
      entity_id: light.wash
      to: 'on'
      id: 'sink'
    - platform: state
      entity_id: binary_sensor.washer_door_button
      to: 'on'
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: 'sink'
          sequence:
            - condition: template
              value_template: "{{ not is_state('light.sink_cool', 'on') }}"        
#            - service: script.tradfri_transition
#              data:
#                entity_id: light.sink_cool
#                color_temp: 153 # white color
#                transition: 2
#                brightness: 254
#              entity_id: light.sink_cool
            - service: light.turn_on
              entity_id: light.sink_cool              
            - service: script.tradfri_transition
              data:
                entity_id: light.w_4
                color_temp: 370 # beige color
                transition: 2
                brightness: 254
              entity_id: light.w_4
      default:
        - service: light.turn_on
          entity_id: light.wash

- alias: 'motion washroom auto-off'
  mode: parallel
  trigger:
    - platform: state
      entity_id: group.motion_showerroom_occupancy
      to: 'off'
      for: 30
    - platform: state
      entity_id: light.wash
      to: 'off'
      for: 30
      id: sink
  condition:
    - condition: template # disable motion light
      value_template: "{{ not is_state('input_boolean.disable_motion_lights', 'on') }}"       
      
  action:
    - choose:
        - conditions:
            - condition: trigger
              id: 'sink'
          sequence:
            - service: light.turn_off
              entity_id: light.sink_all
      default:
        - service_template: light.turn_{{ 'on' if is_state('light.shower', 'on') else 'off' }}
          entity_id: light.wash



#########################################################
#                                                                                                              
#             END OF CONFIGURATION FILE                                                          
#                                                                                                              
#########################################################