#########################################################
#
#             Washroom
#
#########################################################

- alias: 'motion washroom auto-on'
  mode: parallel
  triggers:
    - trigger: template
      value_template: "{{ state_attr('binary_sensor.wash_occupied', 'initiated') == true }}"
    - trigger: template
      value_template: "{{ is_state('binary_sensor.washroom_radar_moving_target', 'on') }}"
    - trigger: state
      entity_id: binary_sensor.washer_door_button
      to: 'on'
      id: 'shower'
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: 'shower'
          sequence:
            - action: light.toggle
              entity_id: light.shower
      default:
        - action: light.turn_on
          entity_id: light.laundry, light.sink, light.vanity

- alias: 'motion washroom auto-off'
  mode: parallel
  triggers:
    - trigger: state
      entity_id: binary_sensor.wash_occupied
      to: 'off'
#  conditions:
#    - condition: template # disable motion light
#      value_template: "{{ not is_state('input_boolean.disable_motion_lights', 'on') }}"
  actions:
    - choose:
        - conditions:
            - condition: template
              value_template: "{{ not is_state('input_boolean.disable_motion_lights', 'on') and now().hour < 21 or now().hour > 7 }}"
          sequence:
            - action: light.turn_on
              entity_id: light.laundry
        - conditions:
            - condition: template
              value_template: "{{ not is_state('input_boolean.disable_motion_lights', 'on') and now().hour > 21 or now().hour < 7 }}"
          sequence:
            - action: light.turn_off
              entity_id: light.laundry
      default:
        - service_template: light.turn_{{ 'on' if is_state('light.shower', 'on') else 'off' }}
          entity_id: light.laundry
        - delay: 10
        - service_template: light.turn_{{ 'on' if is_state('light.shower', 'on') else 'off' }}
          entity_id: light.sink, light.vanity


#########################################################
#
#             END OF CONFIGURATION FILE
#
#########################################################