#########################################################
#
#             Washroom
#
#########################################################

- alias: 'motion washroom auto-on'
  mode: parallel
  triggers:
    - trigger: template # primary trigger
      value_template: "{{ state_attr('binary_sensor.wash_occupied', 'initiated') == true }}"
    - trigger: template # secondary trigger
      value_template: "{{ is_state('binary_sensor.washroom_radar_moving_target', 'on') }}"
    - trigger: state # button trigger for shower room
      entity_id: binary_sensor.washer_door_button
      to: 'on'
      id: 'shower'
  actions:
    - choose:
        - conditions:
            - condition: trigger
              id: 'shower'
          sequence:
            - action: light.toggle
              entity_id: light.shower
      default:
        - action: light.turn_on
          entity_id: light.laundry, light.sink, light.vanity

- alias: 'motion washroom auto-off'
  mode: parallel
  triggers:
    - trigger: template # start nightlight monitoring
      value_template: "{{ state_attr('binary_sensor.wash_occupied', 'nightlight') == true }}"
    - trigger: state
      entity_id: binary_sensor.wash_occupied
      to: 'off'
  conditions:
    - condition: template
      value_template: "{{ not is_state('input_boolean.guest_mode', 'on') }}"
#    - condition: template # disable motion light
#      value_template: "{{ not is_state('input_boolean.disable_motion_lights', 'on') }}"
  actions:
    - choose:
        - conditions:
            - condition: template # stays on during the day between 7am - 11pm
              value_template: "{{ is_state('input_boolean.disable_motion_lights', 'on') and (now().hour > 22 or now().hour > 6) }}"
          sequence: # possibly don't need the template of attr being true #
            - service_template: light.turn_{{ 'off' if state_attr('binary_sensor.wash_occupied', 'nightlight') == true else 'on' }}
              entity_id: light.laundry

#        - conditions:
#            - condition: template # auto off at 11pm and  between 11pm - 7pm
#              value_template: "{{ state_attr('binary_sensor.wash_occupied', 'nightlight') == true or not is_state('input_boolean.disable_motion_lights', 'on') and (now().hour > 22 or now().hour < 7) }}"
#          sequence:
#            - action: light.turn_off
#              entity_id: light.laundry

      default:
        - service_template: light.turn_{{ 'on' if is_state('light.shower', 'on') else 'off' }}
          entity_id: light.laundry
        - delay: 10
        - service_template: light.turn_{{ 'on' if is_state('light.shower', 'on') else 'off' }}
          entity_id: light.sink, light.vanity


#########################################################
#
#             END OF CONFIGURATION FILE
#
#########################################################