# ESP8266 NodeMCU....
# [BC-DD-C2-7A-CC-B4]
substitutions:
  name: sr_sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: 'rice_dwarf'
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.92
    subnet: 255.255.255.0
    gateway: 192.168.1.1

captive_portal:

logger:

api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

sensor:
  - platform: wifi_signal
    name: $name wifi signal

  - platform: adc
    pin: A0
    name: 'sr illuminance'
    unit_of_measurement: lux
    update_interval: 60s

binary_sensor:
  - platform: status
    name: $name dht Status

  - platform: gpio
    pin: D5
    name: 'motion sr occupancy'
    device_class: motion

