# ESP8266 Uno [8C:AA:B5:79:83:92]
substitutions:
  name: aio-wemos
  platform: ESP8266
  board: d1_mini
  oa: oa
  mr: mr

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
#  use_address: aio_wemos.local
  ssid: !secret ssid_1
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.95
    subnet: 255.255.255.0
    gateway: 192.168.1.1
  
captive_portal:

logger:

# Uncomment this if you use Home Assistant
api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

# Sensors
sensor:
  - platform: dht
    model: AM2302
    pin: D6
    temperature:
      name: '$mr temperature'
    humidity:
      name: '$mr humidity'
    update_interval: 40s

  - platform: dht
    model: AM2302
    pin: D7
    temperature:
      name: '$oa temperature'
    humidity:
      name: '$oa humidity'
    update_interval: 40s

  - platform: wifi_signal
    name: $name wifi signal

  - platform: adc
    pin: A0
    name: 'rear Illuminance'
    unit_of_measurement: lux
    update_interval: 40s

binary_sensor:
  - platform: status
    name: $mr dht sensor status
  - platform: status
    name: $oa dht sensor status

  - platform: gpio
    pin: D5
    name: 'motion $mr occupancy'
    device_class: motion

  - platform: gpio
    pin: GPIO4
    name: 'motion g2 occupancy'
    device_class: motion