# ESP8266 Uno [8C:AA:B5:79:83:92]
substitutions:
  name: aio_wemos
  platform: ESP8266
  board: d1_mini

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: 'rice_dwarf'
  password: !secret ssid_pass
  manual_ip:
    static_ip: 192.168.1.95
    subnet: 255.255.255.0
    gateway: 192.168.1.1
#  output_power : 10db
  
captive_portal:

logger:

# Uncomment this if you use Home Assistant
api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

# Sensors
sensor:
  - platform: dht
    model: AM2302
    pin: D6
    temperature:
      name: 'MR Temperature'
    humidity:
      name: 'MR Humidity'
    update_interval: 60s

  - platform: dht
    model: AM2302
    pin: D7
    temperature:
      name: 'OST Temperature'
    humidity:
      name: 'OST Humidity'
    update_interval: 60s

  - platform: wifi_signal
    name: $name WiFi Signal

  - platform: adc
    pin: A0
    name: 'OST Illuminance'
    unit_of_measurement: lux
    update_interval: 60s
#    filters:
#      - lambda: (x * 3.3 / 10000.0) * 2000000.0

binary_sensor:
  - platform: status
    name: MR DHT Sensor Status
  - platform: status
    name: OST DHT Sensor Status

  - platform: gpio
    pin: D5
    name: 'Motion MR Occupancy'
    device_class: motion

