# [D8:13:2A:2E:DB:10]
substitutions:
  name: bt-proxy-livingroom

<<: !include .base.yaml #.221 
<<: !include .base.sensors.yaml 

packages:
  esphome.bluetooth-proxy: github://esphome/firmware/bluetooth-proxy/esp32-generic.yaml@main

esphome:
  name: $name
  name_add_mac_suffix: false


