
substitutions:
  name: bt-proxy-computer
  temp_offset: '-5'
  hum_offset: '10'

esphome:
  name: $name
  platformio_options:
    board_build.flash_mode: dio
  project:
    name: Screek.Human_Sensor
    version: 1w

external_components:
  - source:
      type: git
      url: https://github.com/screekworkshop/custom_components_support_for_screek_1w
      ref: main
    components: [uart, ld2410]

packages:
  aht10: !include components/aht10.yaml
  ld2410B: !include components/ld2410b.yaml

bluetooth_proxy:
  active: true
esp32_ble_tracker:
    scan_parameters:
      window: 900ms
      interval: 1000ms

esp32:
  board: wemos_d1_mini32

<<: !include .base.yaml

i2c: # for aht10
  sda: GPIO21
  scl: GPIO22
  scan: true

uart:
  id: uart_ld2410
  tx_pin: GPIO3
  rx_pin: GPIO1
  baud_rate: 256000
  parity: NONE
  stop_bits: 1

