# ESP8266 NodeMCU.... 40-91-51-50-68-18 [40:91:51:50:68:18]
substitutions:
  name: cabinet-sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid3
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.1.76
    subnet: 255.255.255.0
    gateway: 192.168.1.1

captive_portal:
logger:

api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: gpio
    pin: D1
    name: 'motion cabinet occupancy'
    device_class: motion

  - platform: status
    name: "$name status"
    
switch:
  - platform: restart
    name: "$name Restart"
    icon: mdi:restart    
