# ESP8266 NodeMCU....
substitutions:
  name: computerroom-sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid3
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  reboot_timeout: 0s  
  manual_ip:
    static_ip: 192.168.1.98
    subnet: 255.255.255.0
    gateway: 192.168.1.1

captive_portal:
logger:

mqtt:
  topic_prefix: esphome/$name
  discovery: false
  broker: 192.168.1.20
  username: !secret mqtt_user
  password: !secret mqtt_pass

ota:
  password: !secret ota_pass

sensor:
  - platform: wifi_signal
    name: computerroom wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: gpio
    pin: D2
    name: 'motion computerroom occupancy'
    device_class: motion
    
  - platform: status
    name: "$name status"

switch:
  - platform: restart
    name: "$name Restart"
    icon: mdi:restart    