# [40:91:51:50:68:18]
substitutions:
  name: cr-sensor
  room: computerroom

packages:
  stats: !include components/stats.yaml
  bme280: !include components/bme280.yaml

<<: !include .base.yaml # .119

esphome:
  name: $name
  platform: esp8266
  board: d1_mini

binary_sensor:
  - platform: gpio
    pin: D6
    name: 'motion $name occupancy'
    device_class: motion

#  - platform: status
#    name: $name dht Status

#sensor:
#  - platform: wifi_signal
#    name: $name wifi signal
#    update_interval: 15s
#    filters:
#      - sliding_window_moving_average:
#          window_size: 15
#          send_every: 15

