# [BC:DD:C2:7A:CC:B4]
# https://github.com/CDaxi/esphome-projects/tree/master/airfreshener
substitutions:
  name: "gk-airfreshener"
  counter: Spray counter
  reset: Reset spray counter
#  ssid: !secret ssid3

packages:
  airfresh: !include components/airfresh.yaml

<<: !include .base.yaml #.76

esphome:
  name: $name
  platform: esp8266
  board: d1_mini

sensor:
  - platform: wifi_signal
    name: ${name} wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

binary_sensor:
  - platform: status
    name: ${name} status

