
substitutions:
  name: gk-airfreshener
  room: Genkan # use mdf
  temp_offset: '-.8'
  hum_offset: '9'
  # Timing Intervals: Adjust to suit your Need/Situation.
  # NOTE: Values MUST BE in "quotes"
  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"
  # Plunger Pulse Duration. Range: 55-200
  squirt_pulse: "195ms"
  # Cannister Squirt Capacity
  maxSquirts: "280" #default 290

packages:
  airfresh: !include components/airfresh-v2.yaml
  aht10: !include components/aht10.yaml

<<: !include .base.yaml

esphome:
  name: $name
esp8266:
  board: d1_mini
  restore_from_flash: true
