# ESP8266 192.168.1.74
substitutions:
  name: hallway-sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid2
  password: !secret ssid_pass
  fast_connect : true
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.1.74
    subnet: 255.255.255.0
    gateway: 192.168.1.1
  
logger:

api:
  encryption:
    key: !secret esphome_apikey

ota:
  password: !secret ota_pass

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

  - platform: adc
    pin: A0
    name: '$name illuminance'
    unit_of_measurement: lux
    update_interval: 60s
    filters:
      - lambda: |-
          return (x / 10000.0) * 2000000.0;
          
binary_sensor:
  - platform: gpio
    pin: D1
    name: 'motion hallway occupancy'
    device_class: motion
    
  - platform: gpio
    pin: D7
    name: 'motion g1 occupancy'
    device_class: motion

  - platform: status
    name: "$name status"

switch:
  - platform: restart
    name: "$name Restart"
    icon: mdi:restart