
substitutions:
  name: kt-human-sensor
  temp_offset: '1.5'
  hum_offset: '4'

packages:
  ld2410: !include components/ld2410-v2.yaml
  aht10: !include components/aht10.yaml

<<: !include .base.yaml 

esphome:
  name: $name
esp8266:
  board: d1_mini

status_led:
  pin:
    number: GPIO2
    inverted: false

sensor:
  - platform: wifi_signal
    name: wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

binary_sensor:
  - platform: status
    name: status

