# [40:91:51:4F:1B:91]
# https://www.youtube.com/watch?v=gmUkuQgKljo
# https://www.digi.com/resources/examples-guides/xbee-scent-generator
substitutions:
  name: lr-airfreshener
  temp_offset: "-2"
  hum_offset: "0"
  # Timing Intervals: Adjust to suit your Need/Situation.
  # NOTE: Values MUST BE in "quotes"
  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"
  # Plunger Pulse Duration. Range: 55-100, 3v at 210
  squirt_pulse: "200ms"
  # Cannister Squirt Capacity
  maxSquirts: "300" #max 280

packages:
  ld2410: !include components/ld2410-v2.yaml
  airfresh: !include components/airfresh-v2.yaml
  aht10: !include components/aht10.yaml
  ky038: !include components/ky038.yaml

# This is for ky038
external_components:
  - source:
      type: git
      url: https://github.com/Reubertt/esphome-components
    components: [volume_sensor]

<<: !include .base.yaml

esphome:
  name: $name
esp8266:
  board: d1_mini

status_led:
  pin:
    number: GPIO2 #ESP8266 OnBroad LED
    inverted: false # false=led on

sensor:
  - platform: wifi_signal
    name: wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

binary_sensor:
  - platform: status
    name: status

