# 40:91:51:4F:1B:91
substitutions:
  devicename: lr-airfreshener
  friendly_name: LR Airfreshener
  friendly_suffix_counter: Spray counter
  friendly_suffix_button_spray: Spray
  friendly_suffix_button_reset: Reset spray counter

esphome:
  name: $devicename

esp8266:
  board: esp01_1m

preferences:
  flash_write_interval: 1min

logger:

api:
  encryption:
    key: !secret esphome_apikey
#  password: !secret ota_pass

ota:
  password: !secret ota_pass

wifi:
  ssid: !secret ssid3
  password: !secret ssid_pass
  fast_connect : true
  manual_ip:
    static_ip: 192.168.1.119
    subnet: 255.255.255.0
    gateway: 192.168.1.1

output:
  - platform: esp8266_pwm
    id: motor_forward_pin
    pin: GPIO4
  - platform: esp8266_pwm
    id: motor_reverse_pin
    pin: GPIO5

fan:
  - platform: hbridge
    id: spray_motor
    name: ${friendly_name} Motor
    pin_a: motor_forward_pin
    pin_b: motor_reverse_pin
    # enable_pin: motor_enable
    decay_mode: slow
    internal: true

number:
  - platform: template
    #name: ${friendly_name} ${friendly_suffix_counter}
    icon: mdi:counter
    id: spray_counter
    restore_value: true
    update_interval: 30s
    min_value: 0
    max_value: 400
    mode: box
    step: 1
    optimistic: true
    internal: true

sensor:
  - platform: template
    name: ${friendly_name} ${friendly_suffix_counter}
    icon: mdi:counter
    id: spray_counter_tpl
    state_class: measurement
    unit_of_measurement: ""
    accuracy_decimals: 0
    lambda: |-
      return id(spray_counter).state;
    update_interval: 60s

  - platform: wifi_signal
    name: ${friendly_name} wifi signal
    update_interval: 15s

#  - platform: adc
#    pin: A0
#    name: '${friendly_name} illuminance'
#    unit_of_measurement: lux
#    update_interval: 60s
#    filters:
#      - lambda: |-
#          return (x / 10000.0) * 2000000.0;

binary_sensor:
  - platform: status
    name: ${friendly_name} status

button:
  - platform: template
    name: ${friendly_name} ${friendly_suffix_button_spray}
    id: btn_spray
    icon: mdi:spray
    on_press:
      then:
        if:
          condition:
            not:
              script.is_running: do_spray
          then:
            script.execute: do_spray
  - platform: template
    name: ${friendly_name} ${friendly_suffix_button_reset}
    icon: mdi:restart
    on_press:
      then:
        - number.set:
            id: spray_counter
            value: 0
        - component.update: spray_counter
        - component.update: spray_counter_tpl

script:
  - id: do_spray
    then:
      - number.increment: spray_counter
      - component.update: spray_counter
      - component.update: spray_counter_tpl
      - fan.hbridge.brake: spray_motor
      - fan.turn_on:
          id: spray_motor
          speed: 80
          direction: forward
      - delay: 350ms
      - fan.hbridge.brake: spray_motor
      - fan.turn_on:
          id: spray_motor
          speed: 80
          direction: reverse
      - delay: 200ms
      - fan.hbridge.brake: spray_motor
      - fan.turn_off:
          id: spray_motor
      - delay: 500ms