# [40:91:51:4F:1B:91]
# https://github.com/CDaxi/esphome-projects/tree/master/airfreshener
substitutions:
  name: lr-airfreshener
  room: Lr
  counter: Spray counter
  reset: Reset spray counter

packages:
  ld2410: !include components/ld2410-v2.yaml
  airfresh: !include components/airfresh.yaml

<<: !include .base.yaml

esphome:
  name: $name
esp8266:
  board: d1_mini

i2c:
  sda: D2 # not used
  scl: D3
  scan: true
#  id: bus_a

status_led:
  pin:
    number: GPIO2 #ESP8266 OnBroad LED
    inverted: false # false=led on

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15

binary_sensor:
  - platform: status
    name: $name status

