#ESP8266 with LD1115H Radar Sensor [E0:98:06:91:07:C2]
# https://github.com/rainchi/ESPHome-LD2410
substitutions:
  name: lr-radar
#  room: livingroom
  upper: Lr
  lower: lr

packages:
  ld2410: !include components/ld2410.yaml
  bme280: !include components/bme280.yaml
  adc: !include components/adc.yaml

# https://github.com/robertklep/esphome-custom-component
external_components: # fix for removal of custom component in esphome 2025.xx and up
  - source:
      type: git
      url: https://github.com/esphome/esphome
      ref: refs/tags/2024.12.4
    components: [ custom, custom_component ]

esphome:
  name: $name
  includes:
    - /config/esphome/components/ld2410_uart.h
  on_boot:
    priority: 600
    # ...
    then:
      - lambda: |-
          auto uart_component = static_cast<LD2410 *>(ld2410);
          uart_component->setNumbers(maxMovingDistanceRange, maxStillDistanceRange, noneDuration);
esp8266:
  board: d1_mini

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret esphome_apikey

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  ssid: !secret ssid
  password: !secret ssid_pwd
  fast_connect : true
  power_save_mode: none
  reboot_timeout: 0s
#  use_address: 192.168.1.160
#  manual_ip:
#    static_ip: 192.168.1.51
#    subnet: 255.255.255.0
#    gateway: 192.168.1.1

sensor:
  - platform: wifi_signal
    name: Wifi Signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

switch:
  - platform: restart
    name: Restart
    icon: mdi:restart

binary_sensor:
  - platform: status
    name: status
