# ESP8266 NodeMCU....
# [98:CD:AC:31:B8:E7] NEW
# [50:02:91:FD:4B:26] OLD
substitutions:
  name: lr-sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
#  use_address: lr_sensor.local
  ssid: !secret ssid_1
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.96
    subnet: 255.255.255.0
    gateway: 192.168.1.1
  
captive_portal:

logger:

api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

sensor:
  - platform: dht
    model: AM2302
    pin: D3 #Avoid D4. LED Driven
    temperature:
      name: 'lr temperature'
    humidity:
      name: 'lr humidity'
    update_interval: 50s

  - platform: wifi_signal
    name: $name wifi signal

  - platform: adc
    pin: A0
    name: 'front illuminance'
    unit_of_measurement: lux
    update_interval: 55s

binary_sensor:
  - platform: status
    name: $name dht Status

  - platform: gpio
    pin: D5
    name: 'motion lr occupancy'
    device_class: motion

