# ESP8266 NodeMCU....
# [50:02:91:FD:4B:26]
substitutions:
  name: lr_sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: 'rice_dwarf'
  password: !secret ssid_pass
  manual_ip:
    static_ip: 192.168.1.96
    subnet: 255.255.255.0
    gateway: 192.168.1.1
  output_power : 10db
  
captive_portal:

logger:

# Uncomment this if you use Home Assistant
api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

# Sensors
sensor:
  - platform: dht
    model: AM2302
    pin: D4
    temperature:
      name: 'lr temperature'
    humidity:
      name: 'lr humidity'
    update_interval: 60s

  - platform: wifi_signal
    name: $name wifi signal

  - platform: adc
    pin: A0
    name: 'front illuminance'
    unit_of_measurement: lux
    update_interval: 60s
#    filters:
#      - lambda: (x * 3.3 / 10000.0) * 2000000.0

binary_sensor:
  - platform: status
    name: $name dht Status

  - platform: gpio
    pin: D8
    name: 'motion lr occupancy'
    device_class: motion

