# This is a custom firmware for Human Presence Sensor 1U
# https://screek.io/1u

substitutions:
  name: mr-human-sensor
  room: Mr

esphome:
  name: $name
  platformio_options:
    board_build.flash_mode: dio
    board_build.f_cpu: 80000000L
  on_boot:
    priority: 900
    then:
       lambda: |-
        id(cpu_speed) = ESP.getCpuFreqMHz() ;
  project: 
    name: Screek.Human Presence Sensor
    version: 1U
  min_version: 2023.6.1

globals:
   - id: cpu_speed
     type: int
     restore_value: no
     initial_value: '0'

external_components:
  # - source: github://screek-workshop/custom_components_support_for_screek_1u
  - source:
      type: git
      url: https://github.com/screek-workshop/custom_components_support_for_screek_1u
      ref: master
    # components: [ ld2410, uart ]

esp32:
  board: lolin_s2_mini
  framework:
    type: arduino
    version: 2.0.9
    platform_version: 6.3.2

improv_serial:

logger:
  hardware_uart: uart0

wifi:
  ssid: !secret ssid
  password: !secret ssid_pwd

captive_portal:

api:
  encryption:
    key: !secret esphome_apikey

ota:
  - platform: esphome
    password: !secret ota_pass

web_server:
  port: 80

binary_sensor:
  - platform: status # consolidate
    name: $name Online
    id: ink_ha_connected

  - platform: ld2410
    ld2410_id: ld2410_0
    has_target:
      name: $room Presence
    has_moving_target:
      name: $room Moving Target
    has_still_target:
      name: $room Still Target

sensor:
  - platform: template
    name: $name ESP Cpu Speed
    accuracy_decimals: 0
    unit_of_measurement: Mhz
    lambda: |-
      return (id(cpu_speed));
    entity_category: "diagnostic"

  - platform: template
    id: sys_esp_temperature
    name: $name ESP Temperature
    lambda: return temperatureRead();
    unit_of_measurement: °C
    device_class: TEMPERATURE
    update_interval: 5s
    entity_category: "diagnostic"

  - platform: uptime
    name: $name Uptime
    id: sys_uptime
    update_interval: 10s

  - platform: wifi_signal # consolidate
    name: $name RSSI
    id: wifi_signal_db
    update_interval: 5s
    entity_category: "diagnostic"

  - platform: template
    id: esp_memory
    icon: mdi:memory
    name: $name ESP Free Memory
    lambda: return heap_caps_get_free_size(MALLOC_CAP_INTERNAL) / 1024;
    unit_of_measurement: 'kB'
    state_class: measurement
    entity_category: "diagnostic"

  - platform: ld2410
    ld2410_id: ld2410_0
    moving_distance:
      name: $room Moving Distance
      id: moving_distance
    still_distance:
      name: $room Still Distance
      id: still_distance
    moving_energy:
      name: $room Move Energy
    still_energy:
      name: $room Still Energy
    detection_distance:
      name: $room Detection Distance
    light:
      name: $room Sun Light

light:
  - platform: status_led
    name: $name sys_status
    pin: GPIO15
    internal: True
    restore_mode: ALWAYS_OFF

time:
  - platform: sntp
    id: time_sntp

uart:
  - id: uart_0
    tx_pin: GPIO18
    rx_pin: GPIO33
    baud_rate: 256000
    parity: NONE
    stop_bits: 1

ld2410:
  - id: ld2410_0
    timeout: 150s
    uart_id: uart_0

button:
  - platform: template
    name: "$name Enable LD2410 BLE"
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth
    on_press:
      lambda: |-
        id(ld2410_0) -> ble_control(true);

  - platform: template
    name: "$name Disable LD2410 BLE"
    # disabled_by_default: True
    entity_category: "config"
    icon: mdi:bluetooth-off
    on_press:
      lambda: |-
        id(ld2410_0) -> ble_control(false);

  - platform: template
    name: "$name LD2410 Reboot"
    icon: mdi:radar
    entity_category: "config"
    on_press:
      lambda: |-
        // auto* radar = LD2410Component::get(ld2410); 
        // radar -> roboot();
        id(ld2410_0) -> reboot();

  - platform: restart
    icon: mdi:power-cycle
    name: "$name ESP Reboot"

  - platform: factory_reset
    disabled_by_default: True
    name: $name Factory Reset
    id: factory_reset_all