# ESP32 CAM [10:52:1C:62:EC:48]
substitutions:
  name: security-cam
  platform: ESP32
  board: esp-wrover-kit # esp32dev

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid_1
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.94
    subnet: 255.255.255.0
    gateway: 192.168.1.1

# Fallback portal 
captive_portal:
# Logging
logger:
# Uncomment this if you use Home Assistant
api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

# Sensors
sensor:
   - platform: wifi_signal
     name: '$name WiFi Signal'

esp32_camera:
  external_clock:
    pin: GPIO3 # GPIO3
    frequency: 20MHz
  i2c_pins:
    sda: GPIO26
    scl: GPIO27
  data_pins: [GPIO5, GPIO18, GPIO19, GPIO21, GPIO36, GPIO39, GPIO34, GPIO35]
  vsync_pin: GPIO25
  href_pin: GPIO23
  pixel_clock_pin: GPIO22
  power_down_pin: GPIO32
  name: security
# Image settings
  max_framerate: 1 fps
  resolution: SXGA
  jpeg_quality: 20
  contrast: 2
  saturation: 2

# Flashlight
output:
  - platform: gpio
    pin: GPIO12
    id: gpio_12

light:
  - platform: binary
    output: gpio_12
    name: $name light


