# [0C:B8:15:FE:F3:F4]
substitutions:
  name: security-entrance
  vertical_flip: 'true'

packages:
  cam: !include components/cam.yaml

<<: !include .base.yaml #.244

esphome:
  name: $name
  platform: esp32
  board: nodemcu-32s

sensor:
  - platform: wifi_signal
    name: '$name wifi signal'
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: gpio
    pin: GPIO14
    name: motion entrance occupancy
    device_class: motion    

  - platform: status
    name: "$name status"

switch:
  - platform: restart
    name: "$name Restart"
    icon: mdi:restart    
