#  a0:85:e3:0e:37:94
substitutions:
  name: shoshuriki
#  room: Shoshuriki
  temp_offset: "-1.3"
  hum_offset: "6"

  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"
  # Plunger Pulse Duration. Range: 55-180
  squirt_pulse: "170ms"
  # Cannister Squirt Capacity
  maxSquirts: "1400" #max 1400

packages:
  aht10: !include components/aht10.yaml

<<: !include .base.yaml

i2c: # for aht10
  sda: GPIO6 
  scl: GPIO7
  scan: true

esphome:
  name: $name
  platformio_options:
    board_build.flash_mode: dio
esp32:
  board: seeed_xiao_esp32c3
  variant: esp32c3
  framework:
    type: arduino
    platform_version: 5.4.0

globals:
  # Store the Cannister Percentage
  - id: squirts
    type: float
    restore_value: yes

  # Timer for Hold Button Reset
  - id: press_duration
    type: int
    restore_value: no
    initial_value: '0'

button:
  - platform: template
    name: Alt Button
    icon: mdi:restart
    on_press:
      then:
        - lambda: |-
            ESP_LOGD("Scent-a-Tron", "Can Percentage RESET");
            id(squirts) = 0;
            id(can_level).publish_state(100);
            global_preferences->sync();

binary_sensor: # not working for small glade
  # Unit's Top Button for local Manual "Squirts" and Resetting Cannister Percentage
  - platform: gpio
    name: Button
    disabled_by_default: true
    pin: 
      number: GPIO9 # not physically connected
      inverted: True

    on_press:
      then:
        - lambda: |-
            id(press_duration) = millis();
    on_release:
      then:
        - lambda: |-
            if (millis() - id(press_duration) < 3000) {
            ESP_LOGD("Scent-a-Tron", "The Button Was Pressed!");
            id(theSquirter).turn_on();
            } else {
            ESP_LOGD("Scent-a-Tron", "Can Percentage RESET");
            id(squirts) = 0;
            id(can_level).publish_state(100);
            global_preferences->sync();
            }

select:
  - platform: template
    id: intervalSelect
    name: Interval
    icon: mdi:timer-outline
    optimistic: true
    restore_value: true
    options:
      - "Off"
      - $interval1 Minutes
      - $interval2 Minutes
      - $interval3 Minutes
      - $interval4 Minutes
      - $interval5 Minutes
    on_value:
      then:
        - script.execute: squirtTimer 

script:
  # Script for Auto squirt
  - id: squirtTimer
    mode: restart
    then:
      - while:
          condition:
            lambda: 'return id(intervalSelect).state != "Off";'
          then:
            - delay: !lambda 'return atoi(id(intervalSelect).state.c_str()) * 60000;' # For testing. Default 60000
            - switch.turn_on: theSquirter

switch:
  # The Glade DC Motor
  - platform: gpio
    name: ' '
    id: theSquirter
    icon: mdi:spray
    pin: 
      number: GPIO10  
    on_turn_on:
      then:
        - delay: $squirt_pulse
        - switch.turn_off: theSquirter
        - lambda: |-
            id(squirts) += 1;
            id(can_level).publish_state( (($maxSquirts-id(squirts))/$maxSquirts) * 100 );
            ESP_LOGD("Scent-a-Tron", "I Squirted!");
            global_preferences->sync();

sensor:
  - platform: template
    id: can_level
    name: Can
    device_class: volume
    unit_of_measurement: "Can"
    update_interval: $interval1 min
    lambda: |-
      return (($maxSquirts-id(squirts))/$maxSquirts) * 100;
