# ESP8266 NodeMCU.... 4C:75:25:35:08:7C
substitutions:
  name: sink-sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid3
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: Light
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.1.75
    subnet: 255.255.255.0
    gateway: 192.168.1.1

logger:

api:
  encryption:
    key: !secret esphome_apikey  
  
ota:
  password: !secret ota_pass

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: gpio
    pin: D2
    name: 'motion sink occupancy'
    device_class: motion

  - platform: status
    name: "$name status"
    
switch:
  - platform: restart
    name: "$name Restart"
    icon: mdi:restart    
