#  [98:CD:AC:31:B8:E7]
substitutions:
  name: sr-radar
  temp_offset: '0'
  hum_offset: '0'

packages:
  ld2410c: !include components/ld2410c-gen.yaml
  aht10: !include components/aht10.yaml

esphome:
  name: $name
esp8266:
  board: d1_mini  
  
#  platformio_options:
#    board_build.flash_mode: dio
#  project:
#    name: Screek.Human_Sensor
#    version: 1w

#external_components:
#  - source:
#      type: git
#      url: https://github.com/screekworkshop/custom_components_support_for_screek_1w
#      ref: main
#    components: [ ld2410 ]

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret esphome_apikey

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  ssid: !secret ssid
  min_auth_mode: WPA2
  password: !secret ssid_pwd

