#  [98:CD:AC:31:B8:E7]
substitutions:
  name: sr-radar
  room: shionroom #sr-radar
  upper: Sr
  lower: sr
  temp_offset: '0'
  hum_offset: '0'

packages:
  ld2410: !include components/ld2410.yaml
  aht10: !include components/aht10.yaml

esphome:
  name: $name
  platform: esp8266
  board: d1_mini
  includes:
    - /config/esphome/components/ld2410_uart.h
  on_boot:
    priority: 600
    # ...
    then:
      - lambda: |-
          auto uart_component = static_cast<LD2410 *>(ld2410);
          uart_component->setNumbers(maxMovingDistanceRange, maxStillDistanceRange, noneDuration);

logger:
  baud_rate: 0

api:
  encryption:
    key: !secret esphome_apikey

ota:
  - platform: esphome
    password: !secret ota_pass

wifi:
  ssid: !secret ssid
  password: !secret ssid_pwd
  fast_connect : true
  manual_ip:
    static_ip: 192.168.1.122
    subnet: 255.255.255.0
    gateway: 192.168.1.1

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: status
    name: $name status
