# ESP8266 NodeMCU.... C4-5B-BE-70-D3-D2
substitutions:
  name: sr-sensor
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid1
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  reboot_timeout: 0s
  manual_ip:
    static_ip: 192.168.1.99 
    subnet: 255.255.255.0
    gateway: 192.168.1.1

captive_portal:
logger:

api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

sensor:
  - platform: dht
    model: AM2302
    pin: D3 #Avoid D4 LED Driven. Use D3(GPIO0)
    temperature:
      name: 'sr temperature'
    humidity:
      name: 'sr humidity'
    update_interval: 20s

  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: status
    name: $name dht Status

  - platform: gpio
    pin: D6 # Use D5 D6 D7. No luck with D1 D5
    name: 'motion sr occupancy'
    device_class: motion

switch:
  - platform: restart
    name: "$name Restart"
    icon: mdi:restart

