# ESP8266 NodeMCU....
substitutions:
  name: toilet-airfreshener
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: !secret ssid_1
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
#  manual_ip:
#    static_ip: 192.168.1.89
#    subnet: 255.255.255.0
#    gateway: 192.168.1.1

captive_portal:

logger:

api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

switch:
  - platform: gpio
    name: $name
    id: relay
    pin: D2 # use D1, D2, D5, D6, D7 for relays  was D1
    icon: mdi:spray
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - homeassistant.service:
           service: counter.increment
           data:
             entity_id: counter.toilet_airfreshener
      - delay: 12s
      - switch.turn_off: relay

sensor:
  - platform: dht
    model: AM2302
    pin: D3 #Avoid D4. LED Driven. Use D3
    temperature:
      name: '$name temperature'
    humidity:
      name: '$name humidity'
    update_interval: 30s

  - platform: wifi_signal
    name: $name wifi signal

binary_sensor:
  - platform: status
    name: $name status

  - platform: gpio
    pin: D1 # was D5
    name: 'motion tr1 occupancy'
    device_class: motion
