# ESP8266 NodeMCU....
# [BC-DD-C2-7A-CC-B4]
substitutions:
  name: toilet_airfreshener
  platform: ESP8266
  board: nodemcuv2

esphome:
  name: $name
  platform: $platform
  board: $board

wifi:
  ssid: 'rice_dwarf'
  password: !secret ssid_pass
  fast_connect : true
  power_save_mode: none
  manual_ip:
    static_ip: 192.168.1.89
    subnet: 255.255.255.0
    gateway: 192.168.1.1

captive_portal:

logger:

api:
  password: !secret ota_pass
ota:
  password: !secret ota_pass

switch:
  - platform: gpio
    name: $name
    id: relay
    pin: D1 # use D1, D2, d5, d6, d7 for relays
    icon: mdi:spray
    restore_mode: ALWAYS_OFF
    on_turn_on:
      - delay: 12s
      - switch.turn_off: relay

sensor:
  - platform: wifi_signal
    name: $name wifi signal

binary_sensor:
  - platform: status
    name: $name status

  - platform: gpio
    pin: D5
    name: 'motion tr1 occupancy'
    device_class: motion

