# MAC: D8:C8:0C:16:44:96
substitutions:
  manufacturer: Tuya
  model: hc-s050-wifi
  name: usb-relay-adapter1

esphome:
  name: usb-relay-adapter1
bk72xx:
  board: generic-bk7231n-qfn32-tuya

#<<: !include .base.yaml  

wifi:
  ssid: !secret ssid
  password: !secret ssid_pwd

logger:
#  level: WARN
  baud_rate: 0
#  hardware_uart: uart0

api:
  encryption:
    key: !secret esphome_apikey

ota:
  - platform: esphome
    password: !secret ota_pass

switch:
  - platform: gpio
    id: relay
    name: Relay
    pin: P7
    restore_mode: RESTORE_DEFAULT_OFF

light:
  - platform: status_led
    name: Status LED
    disabled_by_default: true
    entity_category: diagnostic
    pin:
      number: P6
      inverted: true

binary_sensor:
  - platform: gpio
    id: btn
    pin:
      number: P8
      inverted: true
      mode:
        input: true
        pullup: true
    name: Side button
    on_release:
      then:
        - switch.toggle: relay