# [40:91:51:4F:90:90] THIS D1 MINI REQUIRES DAILY REBOOTS
substitutions:
  name: washroom-radar
  upper: Wr
  lower: wr

packages:
  ld2410: !include components/ld2410.yaml

<<: !include .base.yaml # .186

esphome:
  name: $name
  platform: esp8266
  board: d1_mini
  includes:
    - /config/esphome/components/ld2410_uart.h
  on_boot:
    priority: 600
    # ...
    then:
      - lambda: |-
          auto uart_component = static_cast<LD2410 *>(ld2410);
          uart_component->setNumbers(maxMovingDistanceRange, maxStillDistanceRange, noneDuration);

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: status
    name: $name status