substitutions:
  name: wc-airfreshener
  room: Wc

  temp_offset: '0'
  hum_offset: '0'
  # Timing Intervals: Adjust to suit your Need/Situation.
  # NOTE: Values MUST BE in "quotes"
  interval1: "5"
  interval2: "15"
  interval3: "30"
  interval4: "60"
  interval5: "120"
  # Plunger Pulse Duration. Range: 55-200
  squirt_pulse: "200ms"
  # Cannister Squirt Capacity
  maxSquirts: "300" #default 280

packages:
  ld2410: !include components/ld2410-v2.yaml
  airfresh: !include components/airfresh-v2.yaml
  aht10: !include components/aht10.yaml

<<: !include .base.yaml  

esphome:
  name: $name
esp8266:
  board: d1_mini
  restore_from_flash: true

status_led:
  pin:
    number: GPIO2 #ESP8266 OnBroad LED
    inverted: true # false=led on

sensor:
  - platform: wifi_signal
    name: $name wifi signal
    update_interval: 15s
    filters:
      - sliding_window_moving_average:
          window_size: 15
          send_every: 15
          send_first_at: 1

binary_sensor:
  - platform: status
    name: $name status
