###############################################################################
#   @author           :   Duc Su
#   @date              :   08/14/2022
#   @package        :   Database
#   @description    :   Recorder and Logger Configurations
###############################################################################

recorder:
#  db_url: !secret MySQL_login
  db_url: sqlite:////media/hassio_db/home-assistant_v2.db
  purge_keep_days: 32
  exclude:
    domains:
      - group
      - automation
      - camera
      - media_player
      - scene
      - script
      - updater
    entities:
      - sun.sun
      - sensor.date_time
      - sensor.date
      - sensor.time_online
      - sensor.moon
      - sensor.month_is
      - sensor.time
      - sensor.today_is
      - sensor.time_utc
      - sensor.last_boot # comes from 'systemmonitor' sensor platform
      - sensor.devices_with_low_battery

sensor:
  - platform: template
    sensors:
      home_assistant_v2_db_size_gb:
        friendly_name: "SQLite Usage GB"
        unit_of_measurement: 'GB'
        value_template: "{{ '{:.2f}'.format((states('sensor.home_assistant_v2_db_size') | float(0) * 0.001)) }}"

logbook:
  include:
    domains:
      - media_player
      - automation
      - script
      - light
      - switch
      - device_tracker
      - input_boolean
      - person

# Lets try to make the logs less chatty and more fine tuned.
logger:
  default: error
  logs:
    homeassistant.core: warning
    homeassistant.loader: error
    homeassistant.components.recorder: error # to spot db issues
    homeassistant.config_entries: error
    homeassistant.setup: error
    homeassistant.helpers.entity: critical
    homeassistant.components.automation: error
    homeassistant.components.waze_travel_time: error
    homeassistant.components.statistics.sensor: critical
    homeassistant.helpers.event: critical

history:
  include:
    domains:
      - sensor
      - switch
      - media_player
      - light
      - scene
      - automation
