#########################################################
#
#             Door Lock Automations
#
#########################################################


input_boolean: 
  duc_unlock_door:
  eri_unlock_door:

automation:

  - alias: Auto Unlock Door
    triggers:
      - trigger: state
        entity_id: binary_sensor.entrance_moving_target
        from: 'off'
        to: 'on'
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: template # duc
                value_template: "{{ is_state('input_boolean.duc_unlock_door', 'on') }}"
              - condition: state 
                entity_id: input_boolean.duc_unlock_door
                to: 'on'
              - condition: template
                value_template: "{{ is_state('device_tracker.id', 'home') and is_state('device_tracker.duc_bermuda_bermuda_tracker', 'home') }}"
              - condition: template
                value_template: >- 
                  {%- set trig = (now() - states.device_tracker.duc_bermuda_bermuda_tracker.last_changed).seconds -%}
                    {{ trig <= 60 }}     
              - condition: template
                value_template: "{{ is_state('lock.lock_pro_8d0a', 'locked') }}"
            sequence:
              - action: lock.open
                entity_id: lock.lock_pro_8d0a
              - action: input_boolean.turn_off
                entity_id: input_boolean.duc_unlock_door

        default: []

#  - alias: Door Lock Automation
#    triggers:
#      - trigger: state
#        entity_id: binary_sensor.entrance_moving_target
#        from: 'off'
#        to: 'on'
#    conditions:
#      - condition: template
#        value_template: "{{ is_state('device_tracker.id', 'home') and is_state('device_tracker.duc_bermuda_bermuda_tracker', 'home') }}"
#        value_template: >- 
#          {%- set trig = (now() - states.device_tracker.duc_bermuda_bermuda_tracker.last_changed).seconds -%}
#            {{ trig <= 60 }}     
#      - condition: template
#        value_template: "{{ is_state('lock.lock_pro_8d0a', 'locked') }}"

#    actions:
#      - action: lock.open
#        entity_id: lock.lock_pro_8d0a

















#########################################################
#
#             END OF CONFIGURATION FILE
#
#########################################################