###############################################################################
#   @author          :   Duc Su 
#   @date              :   6/28/2025
#   @package        :   Events Triggers
#   @description    :   Automations 
###############################################################################

automation:
  - alias: AIO Controller Events
    id: aio_controller_events
    triggers:
      - trigger: state
        entity_id: event.aio_controller_action
        to: ~
    conditions:
      - condition: template
        value_template: "{{trigger.from_state.state != 'unavailable'}}"
    actions:
      - choose:
        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'brightness_up_click'}}"
          sequence:
          - action: script.turn_on
            target:
              entity_id: script.dining_lights_toggle
        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'brightness_down_click'}}"
          sequence:
          - action: light.toggle
            target:
              entity_id: light.living

        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'arrow_left_click'}}"
          sequence:
          - action: script.turn_on
            target:
              entity_id: script.cr_curtains_toggle
        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'arrow_right_click'}}"
          sequence:
          - action: script.turn_on
            target:
              entity_id: script.lr_curtains_toggle

        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'arrow_left_hold'}}"
          sequence:
          - action: script.turn_on
            target:
              entity_id: script.lr_ac_cool_toggle # Normal cool

#          - action: input_select.select_option
#            target:
#              entity_id: input_select.lr_ac_mode
#            data:
#              option: Powerful Cool






        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'arrow_right_hold'}}"
          sequence:
          - action: script.turn_on
            target:
              entity_id: script.lr_ac_heat_toggle # Normal heat

        - conditions:
          - condition: template
            value_template: "{{trigger.to_state.attributes.event_type == 'toggle'}}"
          sequence:
          - action: light.turn_off
            target:
              entity_id:
                - light.living
                - light.ceiling_fan_light