###############################################################################
#   @author          :   Duc Su
#   @date             :   09/3/2024
#   @package        :  Flightradar24
#   @description    :  Tracking aircrafts.
###############################################################################


template:
  - trigger:
      - platform: event
        event_type: flightradar24_exit
    sensor:
      - unique_id: flightradar24_last_5_flights
        name: "FlightRadar24 Last 5 Flights"
        state: >-
          {% set flight = trigger.event.data %}
          {{ flight.flight_number }} - {{ flight.airline_short }} - {{ flight.aircraft_model }} ({{ flight.aircraft_registration }})
          {{ flight.airport_origin_city }} > {{ flight.airport_destination_city }}
        attributes:
          flights: >-
            {% set n = 5 %}
            {% set m = this.attributes.flights | count | default(0) %}
            {{ [ trigger.event.data ] + 
               ( [] if m == 0 else 
                 this.attributes.flights[0:n-1] )
            }}
          icon: mdi:airplane








automation:
  - alias: 'Flight entry notification'
    triggers:
      - trigger: event
        event_type: flightradar24_entry
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
              - condition: template 
                value_template: "{{ trigger.event.data.airline | lower | regex_search('police|fire|safety|operation|university|shizuoka|kawasaki|tohohu|teikyo|okayama|hiratagakuen|asahi') }}"
            sequence:
              - action: notify.amberthebot
                data:
                  message: >-
                    🚁{{ trigger.event.data.airline }} is flying in your neighborhood.
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
              - condition: template 
                value_template: "{{ trigger.event.data.airline | lower | regex_search('private owner|honda|none|Private owner') }}"
              - condition: template 
                value_template: "{{ trigger.event.data.callsign | lower | regex_search('blocked|none|n') }}"
            sequence:
              - action: notify.amberthebot
                data:
                  message: >-
                    ‼️ No flight plan. The aircraft is either private or goverment operated.

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'jcbFT24' and is_state('person.duc', 'jcb') }}"
              - condition: template 
                value_template: "{{ trigger.event.data.airline | lower | regex_search('police|fire|safety|operation|university|shizuoka|kawasaki|tohohu|teikyo|okayama|hiratagakuen|asahi') }}"
            sequence:
              - action: notify.amberthebot
                data:
                  message: >-
                    🚁{{ trigger.event.data.airline }} is flying in your neighborhood.
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'jcbFT24' and is_state('person.duc', 'jcb') }}"
              - condition: template 
                value_template: "{{ trigger.event.data.airline | lower | regex_search('private owner|honda|none|Private owner') }}"
              - condition: template 
                value_template: "{{ trigger.event.data.callsign | lower | regex_search('blocked|none|n') }}"
            sequence:
              - action: notify.amberthebot
                data:
                  message: >-
                    ‼️ No flight plan. The aircraft is either private or goverment operated.

          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
            sequence:
              - action: notify.amberthebot
                data:
                  message: >-
                    📍The plane you hear now is from {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}] at {{ "{:,.0f}".format(trigger.event.data.altitude) }} ft. It comes from {{ trigger.event.data.airport_origin_city }} in {{ trigger.event.data.airport_origin_country_name }} and is on its way to {{ trigger.event.data.airport_destination_city }}.
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'jcbFT24' and is_state('person.duc', 'jcb') }}"
            sequence:
              - action: notify.amberthebot
                data:
                  message: >-
                    💼The plane you hear now is from {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}] at {{ "{:,.0f}".format(trigger.event.data.altitude) }} ft. It comes from {{ trigger.event.data.airport_origin_city }} in {{ trigger.event.data.airport_origin_country_name }} and is on its way to {{ trigger.event.data.airport_destination_city }}.
        default: []

  - alias: 'Scheduled flight takes off'
    triggers:
      - trigger: event
        event_type: flightradar24_tracked_took_off
    actions:
      - action: notify.amberthebot
        data:
          message: >-
             The plane you hear now is from {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}]. It took off from {{ trigger.event.data.airport_origin_city }} in {{ trigger.event.data.airport_origin_country_name }} and is on its way to {{ trigger.event.data.airport_destination_city }}.

