###############################################################################
#   @author          :   Duc Su
#   @date             :   09/3/2024
#   @package        :  Flightradar24
#   @description    :  Tracking aircrafts.
###############################################################################


template:
  - trigger:
      - platform: event
        event_type: flightradar24_exit
    sensor:
      - unique_id: flightradar24_last_5_flights
        name: "FlightRadar24 Last 5 Flights"
        state: >-
          {% set flight = trigger.event.data %}
          {{ flight.flight_number }} - {{ flight.airline_short }} - {{ flight.aircraft_model }} ({{ flight.aircraft_registration }})
          {{ flight.airport_origin_city }} > {{ flight.airport_destination_city }}
        attributes:
          flights: >-
            {% set n = 5 %}
            {% set m = this.attributes.flights | count | default(0) %}
            {{ [ trigger.event.data ] +
               ( [] if m == 0 else
                 this.attributes.flights[0:n-1] )
            }}
          icon: mdi:airplane


automation:
  - alias: 'Flight entry notification'
    triggers:
      - trigger: event
        event_type: flightradar24_entry
    conditions: []
    actions:
      - choose:
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
              - condition: template
                value_template: "{{ trigger.event.data.airline | lower | regex_search('airx|maritime|police|fire|safety|operation|university|shizuoka|kawasaki|tohohu|teikyo|okayama|hiratagakuen|asahi') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    🚁{{ trigger.event.data.airline }} is flying over Kawaguchi.
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
              - condition: template
                value_template: "{{ trigger.event.data.callsign | lower | regex_search('private owner|null|blocked|none|n') }}"
              - condition: template
                value_template: "{{ trigger.event.data.airline | lower | regex_search('null|unknown|private owner|honda airways|none') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    ‼️ No flight plan. The aircraft is either private or goverment operated.

# TESTING
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
              - condition: template
                value_template: "{{ trigger.event.data.airport_destination_city | lower | regex_search('null|unknown|blocked|none|n') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    🚁{{ trigger.event.data.airline }} is flying over Kawaguchi and has not filed a flight plan.




          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'jcbFT24' and is_state('person.duc', 'jcb') }}"
              - condition: template
                value_template: "{{ trigger.event.data.airline | lower | regex_search('airx|maritime|police|fire|safety|operation|university|shizuoka|kawasaki|tohohu|teikyo|okayama|hiratagakuen|asahi') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    🚁{{ trigger.event.data.airline }} is flying over Edogawa.
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'jcbFT24' and is_state('person.duc', 'jcb') }}"
              - condition: template
                value_template: "{{ trigger.event.data.callsign | lower | regex_search('null|blocked|none|n') }}"
              - condition: template
                value_template: "{{ trigger.event.data.airline | lower | regex_search('null|unknown|private owner|honda|none|Private owner|None') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    ‼️ No flight plan. The aircraft is either private or goverment operated.


# TESTING
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'jcb') }}"
              - condition: template
                value_template: "{{ trigger.event.data.airport_destination_city | lower | regex_search('null|blocked|none|n') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    🚁{{ trigger.event.data.airline }} is flying over Edogawa and has not filed a flight plan.




          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'homeFT24' and is_state('person.duc', 'home') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    📍The plane you hear now is from {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}] at {{ "{:,.0f}".format(trigger.event.data.altitude) }} ft. It comes from {{ trigger.event.data.airport_origin_city }} in {{ trigger.event.data.airport_origin_country_name }} and is on its way to {{ trigger.event.data.airport_destination_city }}.
          - conditions:
              - condition: template
                value_template: "{{ trigger.event.data.tracked_by_device == 'jcbFT24' and is_state('person.duc', 'jcb') }}"
            sequence:
              - action: script.text_notify
                data:
                  who: amber
                  message: >-
                    💼The plane you hear now is from {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}] at {{ "{:,.0f}".format(trigger.event.data.altitude) }} ft. It comes from {{ trigger.event.data.airport_origin_city }} in {{ trigger.event.data.airport_origin_country_name }} and is on its way to {{ trigger.event.data.airport_destination_city }}.
        default: []


  - alias: 'Scheduled flight takes off'
    triggers:
      - trigger: event
        event_type: flightradar24_tracked_took_off
    actions:
      - action: script.text_notify
        data:
          who: amber
          message: >-
            An update for flight {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}]. It took off from {{ trigger.event.data.airport_origin_city }} in {{ trigger.event.data.airport_origin_country_name }} and is on its way to {{ trigger.event.data.airport_destination_name }} in {{ trigger.event.data.airport_destination_city }}.
            [Open FlightRadar](https://www.flightradar24.com/{{ trigger.event.data.callsign }})

  - alias: 'Scheduled flight Landed'
    triggers:
      - trigger: event
        event_type: flightradar24_tracked_landed
    actions:
      - action: script.text_notify
        data:
          who: amber
          message: >-
            An update for flight {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}]. It landed at {{ trigger.event.data.airport_destination_name }} in {{ trigger.event.data.airport_destination_city }} on {{ as_timestamp(now(),0)|timestamp_custom("%Y-%m-%d %H:%M") }} local.

# TEST
      - action: script.email_notify
        data:
          who: renee
          title: Flight Update
          message: >-
            An update for flight {{ trigger.event.data.airline }}\[{{ trigger.event.data.callsign }}]. It landed at {{ trigger.event.data.airport_destination_name }} in {{ trigger.event.data.airport_destination_city }} on {{ as_timestamp(now(),0)|timestamp_custom("%Y-%m-%d %H:%M" ) }} local.
