
# Quick Look Mobile. Dummy controls
automation:
- alias: "QLM Climate Change"
  triggers:
    - trigger: state
      entity_id:
        - input_select.lr_ac_mode
        - input_select.mr_ac_mode
        - input_select.sr_ac_mode
  actions:
    - action: climate.set_hvac_mode
      target:
        entity_id: "climate.{{ trigger.entity_id.split('.')[1] }}"
      data:
        hvac_mode: >
          {% set hvac_modes = {
            'Off': 'off',
            'Fan': 'fan_only',
            'Ai Auto': 'auto',
            'Man Auto': 'auto',
            'Powerful Cool': 'cool',
            'Normal Cool': 'cool',
            'Silent Cool': 'cool',
            'Manual Cool': 'cool',
            'Powerful Heat': 'heat',
            'Normal Heat': 'heat',
            'Silent Heat': 'heat',
            'Manual Heat': 'heat',
            'Normal Humidifier': 'fan_only'
          } %}
          {{ hvac_modes[states(trigger.entity_id)] }}


############################
#
# This file should not be modified directly. 
# To add or remove entities to monitor, 
# Please modify the 'quick_look_mobile_macros.jinja' file 
# Located in the '/custom_templates' folder.
#
############################


template:
  - sensor:

############################
#
# SECURITY MONITORING
#
############################

# ALARMS :
      - name: some alarms are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_alarms_are_on %}
          {{ some_alarms_are_on().split(',')[0] }}

      - name: alarms count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_alarms_are_on %}
          {{ some_alarms_are_on().split(',')[1] }}



# DOORS & WINDOWS :
      - name: some contact sensors are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_contact_sensors_are_on %}
          {{ some_contact_sensors_are_on().split(',')[0] }}

      - name: contact sensors count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_contact_sensors_are_on %}
          {{ some_contact_sensors_are_on().split(',')[1] }}


# PRESENCES :
      - name: some occupancy sensors are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_occupancy_sensors_are_on %}
          {{ some_occupancy_sensors_are_on().split(',')[0] }}

      - name: occupancy sensors count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_occupancy_sensors_are_on %}
          {{ some_occupancy_sensors_are_on().split(',')[1] }}


    # LOCKS :
      - name: some locks are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_locks_are_on %}
          {{ some_locks_are_on().split(',')[0] }}

      - name: locks count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_locks_are_on %}
          {{ some_locks_are_on().split(',')[1] }}


############################
#
# AIR MONITORING
#
############################


# CLIMATES :
      - name: some climates are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_climates_are_on %}
          {% set count = some_climates_are_on().split(',')[1]|int %}
          {{ 'on' if count > 0 else 'off' }}


      - name: climates dominance
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_climates_are_on %}
          {{ some_climates_are_on().split(',')[0] }}


      - name: climates count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_climates_are_on %}
          {{ some_climates_are_on().split(',')[1] }}


    # FANS :
      - name: some fans are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_fans_are_on %}
          {{ some_fans_are_on().split(',')[0] }}


      - name: fans count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_fans_are_on %}
          {{ some_fans_are_on().split(',')[1] }}




############################
#
# LIGHT
#
############################

# LIGHT BULBS :
      - name: some lights are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_lights_are_on %}
          {{ some_lights_are_on().split(',')[0] }}

      - name: lights count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_lights_are_on %}
          {{ some_lights_are_on().split(',')[1] }}


      - name: some covers are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_covers_are_on %}
          {{ some_covers_are_on().split(',')[0] }}


      - name: covers count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_covers_are_on %}
          {{ some_covers_are_on().split(',')[1] }}



############################
#
# MEDIA PLAYERS MONITORING
#
############################

# AUDIO PLAYERS :
      - name: some audio players are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_audio_players_are_on %}
          {{ some_audio_players_are_on().split(',')[0] }}

      - name: audio players count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_audio_players_are_on %}
          {{ some_audio_players_are_on().split(',')[1] }}


# VIDEO PLAYERS :
      - name: some video players are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_video_players_are_on %}
          {{ some_video_players_are_on().split(',')[0] }}

      - name: video players count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_video_players_are_on %}
          {{ some_video_players_are_on().split(',')[1] }}



############################
#
# EQUIPMENT MONITORING
#
############################

# DEVICES (SWITCHES, VACUUMS, SENSORS, etc) :
      - name: some devices are on
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_devices_are_on %}
          {{ some_devices_are_on().split(',')[0] }}


      - name: devices count
        state: >
          {% from 'quick_look_mobile_macros.jinja' import some_devices_are_on %}
          {{ some_devices_are_on().split(',')[1] }}
