###############################################################################
#   @author         :   Duc Su 
#   @date           :   03/20/2022
#   @package        :   Sysmon
#   @description    :   A collection of Home Assistant and Pi Sensors. Using ws1 server to perform test every 30mins.
###############################################################################

sensor:
  - platform: mqtt
    name: "Speedtest Result"
    state_topic: "house/speedtest/result"
    json_attributes_topic: "house/speedtest/result"    
    json_attributes_template: "{{ value_json.attributes | tojson }}"
    value_template: "{{ value_json.state }}"

  - platform: template
    sensors:
# Speedtest Results
      speedtest_download:
        value_template: '{{ states.sensor.speedtest_result.attributes["download"] }}'
        unique_id: speeddown
      speedtest_upload:
        value_template: '{{ states.sensor.speedtest_result.attributes["upload"] }}'
        unique_id: speedup
      speedtest_ping:
        value_template: '{{ states.sensor.speedtest_result.attributes["ping"] }}'
        unique_id: speedping
      speedtest_lastrun:
        value_template: '{{ states.sensor.speedtest_result.attributes["time_run"] }}'
        unique_id: speedtimerun

  - platform: statistics
    name: Internet Test Down
    entity_id: sensor.speedtest_download
    state_characteristic: value_max
    max_age:
      days: 7
  - platform: statistics
    name: Internet Test Up
    entity_id: sensor.speedtest_upload
    state_characteristic: value_max
    max_age:
      days: 7            