###############################################################################
#   @author         :   Duc Su
#   @date           :   11/13/2024
#   @package        :   TIME
#   @description    :   Various time sensors, automations
###############################################################################

sensor:
  - platform: time_date
    display_options:
      - 'time'
      - 'date'
      - 'date_time'
      - 'date_time_utc'
      - 'date_time_iso'
      - 'time_date'
      - 'time_utc'

template:
  - sensor:
      - name: 'Period of the day'
        unique_id: period_of_the_day
        state: >-
          {% set elevation = state_attr('sun.sun', 'elevation') %}
          {% set rising = state_attr('sun.sun', 'rising') %}
          {%- if elevation <= -7 -%}
            night
          {%- elif -7 < elevation <= -1 -%}
            {{ 'dawn' if rising else 'dusk' }}
          {%- else -%}
            day
          {%- endif -%}light
        icon: >-
          {% set elevation = state_attr('sun.sun', 'elevation') %}
          {% set rising = state_attr('sun.sun', 'rising') %}
          {%- if elevation <= -7 -%}
            mdi:weather-night
          {%- elif -7 < elevation <= -1 -%}
            mdi:weather-sunset-{{ 'up' if rising else 'down' }}
          {% else %}
            mdi:weather-sunny
          {% endif %}


      - name: 'Today is'
        unique_id: aa24c0d6-c263-483c-93cd-c6aff1bb146a
        state: "{{ ['Monday','Tuesday','Wednesday','Thursday','Friday','Saturday','Sunday'][now().weekday()] }}"
      - name: 'Month is'
        unique_id: 2f43d01a-6661-40f7-964b-2650204881cd
        state: "{{ ['January','February','March','April','May','June','August','September','October','November','December'][now().month-2] }}"

      - name: Human Time
        unique_id: human_time
        state: >
          {% set hour = now().strftime('%-H') | int(0) %}
          {% set minute = now().minute | int(0) %}

          {# Determine part of the day #}
          {% if hour >= 0 and hour < 6 %}
            {% set timeofday = "at night" %}
          {% elif hour >= 6 and hour < 12 %}
            {% set timeofday = "in the morning" %}
          {% elif hour >= 12 and hour < 18 %}
            {% set timeofday = "in the afternoon" %}
          {% else %}
            {% set timeofday = "in the evening" %}
          {% endif %}

          {# Calculate 12-hour notation for display #}
          {% set display_hour = hour % 12 %}
          {% if display_hour == 0 %}{% set display_hour = 12 %}{% endif %}

          {# Calculate next hour for half/quarter notation #}
          {% set next_hour = (hour) % 24 %}
          {% set next_display_hour = next_hour % 12 %}
          {% if next_display_hour == 0 %}{% set next_display_hour = 12 %}{% endif %}

          {# Generate the time in Dutch spoken format #}
          {% if minute == 0 %}
            {{ display_hour }} 0'clock {{ timeofday }}

          {% elif minute == 1 %}
            {{ minute }} minute past {{ display_hour }} {{ timeofday }}

          {% elif minute >= 2 and minute <= 14 %}
            {{ minute }} minutes past {{ display_hour }} {{ timeofday }}

          {% elif minute == 15 %}
            quarter past {{ display_hour }} {{ timeofday }}

          {% elif minute >= 16 and minute <= 29 %}
            {{ 30 - minute }} minutes to half past {{ next_display_hour }} {{ timeofday }}

          {% elif minute == 30 %}
            half {{ next_display_hour }} {{ timeofday }}

          {% elif minute == 31 %}
            {{ minute - 30 }} minute past half {{ next_display_hour }} {{ timeofday }}

          {% elif minute >= 32 and minute <= 44 %}
            {{ minute - 30 }} minutes past half {{ next_display_hour }} {{ timeofday }}

          {% elif minute == 45 %}
            a quarter to {{ next_display_hour }} {{ timeofday }}

          {% elif minute == 59 %}
            {{ 60 - minute }} minute to {{ next_display_hour }} {{ timeofday }}

          {% else %}
            {{ 60 - minute }} minutes to {{ next_display_hour }} {{ timeofday }}
          {% endif %}

        icon: >
          {% set hour = now().strftime('%-H') | int(0) %}
          {% if hour >= 0 and hour < 6 %}
            mdi:weather-night
          {% elif hour >= 6 and hour < 12 %}
            mdi:weather-sunset-up
          {% elif hour >= 12 and hour < 18 %}
            mdi:weather-sunny
          {% else %}
            mdi:weather-sunset-down
          {% endif %}



      - name: 'School Start Days2go'
        unique_id: 9d1945c9-d043-4f59-9ea0-524bd1d306dc
        unit_of_measurement: 'Days'
        state: "{{ ((state_attr('input_datetime.school_first_day', 'timestamp')-as_timestamp(now())) | int /86400) | round(0) }}"
      - name: 'School End Days2go'
        unique_id: 3852ec14-b6a9-4c4b-bb09-37fefddf1cb8
        unit_of_measurement: 'Days'
        state: "{{ ((state_attr('input_datetime.school_last_day', 'timestamp')-as_timestamp(now())) | int /86400) | round(0) }}"
      - name: 'Vacation Days2go' # No upcoming vacation will cause error in log.
        unique_id: bd85ebff-50dc-4af5-addf-6b92a5ba71d1
        unit_of_measurement: 'Days'
        state: >
          {% if state_attr('calendar.vacation', 'start_time') %}
            {{ ((as_timestamp(strptime(state_attr('calendar.vacation', 'start_time'), '%Y-%m-%d'))-as_timestamp(now())) | int /86400) | round(0) }}
          {% else %}
            999
          {% endif %}

#      - name: 'School Tomorrow'
#        unique_id: cace00f8-bf49-4206-85ea-2be58c98f178
#        state: >-
#          {%- set tt=(as_timestamp(now())+ (86400)) | timestamp_custom("%Y-%m-%d",true) %}
#          {% if states.calendar.shion_school.attributes.start_time == tt + " 08:15:00" %}
#            on
#          {% else %}
#            off
#          {% endif %}


  - binary_sensor:
      - name: 'School Tomorrow'
        unique_id: cace00f8-bf49-4206-85ea-2be58c98f179
        state: >-
          {% set tomorrow=as_timestamp(state_attr('calendar.shion_school','start_time')) | timestamp_custom("%Y-%m-%d",true) %}
          {% set next_event=(now().date() + timedelta(days=1)) | string %}
          {{ tomorrow == next_event }}